import { BotGroup } from '../../../shared/schema';

export function generateGroupHandlers(groups: BotGroup[]): string {
  let code = '';
  // Добавляем обработчики для групп
  if (groups && groups.length > 0) {
    code += '\n# Обработчики для работы с группами\n';
    code += '@dp.message(F.chat.type.in_(["group", "supergroup"]))
';
    code += 'async def handle_group_message(message: types.Message):\n';
    code += '    """\n';
    code += '    Обработчик сообщений в группах\n';
    code += '    """\n';
    code += '    chat_id = message.chat.id\n';
    code += '    user_id = message.from_user.id\n';
    code += '    username = message.from_user.username or "Неизвестный"\n';
    code += '    \n';
    code += '    # Проверяем, является ли группа подключенной\n';
    code += '    group_name = None\n';
    code += '    for name, config in CONNECTED_GROUPS.items():\n';
    code += '        if config.get("id") and str(config["id"]) == str(chat_id):\n';
    code += '            group_name = name\n';
    code += '            break\n';
    code += '    \n';
    code += '    if group_name:\n';
    code += '        logging.info(f"📢 Сообщение в подключенной группе {group_name}: {message.text[:50]}... от @{username}")\n';
    code += '        \n';
    code += '        # Здесь можно добавить логику обработки групповых сообщений\n';
    code += '        # Например, модерация, автоответы, статистика и т.д.\n';
    code += '        \n';
    code += '        # Сохраняем статистику сообщений\n';
    code += '        try:\n';
    code += '            await save_group_message_stats(chat_id, user_id, message.text)\n';
    code += '        except Exception as e:\n';
    code += '            logging.error(f"Ошибка сохранения статистики группы: {e}")\n';
    code += '    \n';
    code += '# Функция для сохранения статистики групповых сообщений\n';
    code += 'async def save_group_message_stats(chat_id: int, user_id: int, message_text: str):\n';
    code += '    """\n';
    code += '    Сохраняет статистику сообщений в группе\n';
    code += '    """\n';
    code += '    if db_pool:\n';
    code += '        try:\n';
    code += '            async with db_pool.acquire() as conn:\n';
    code += '                # Здесь можно добавить логику сохранения статистики в БД\n';
    code += '                await conn.execute(\n';
    code += '                    """\n';
    code += '                    INSERT INTO group_activity (chat_id, user_id, message_length, created_at) \n';
    code += '                    VALUES ($1, $2, $3, $4)\n';
    code += '                    ON CONFLICT DO NOTHING\n';
    code += '                    """,\n';
    code += '                    chat_id, user_id, len(message_text or ""), get_moscow_time()\n';
    code += '                )\n';
    code += '        except Exception as e:\n';
    code += '            logging.error(f"Ошибка при сохранении статистики группы: {e}")\n';
    code += '    \n';
    code += '\n    // Добавляем обработчик новых участников в группе\n';
    code += '    code += '@dp.message(F.new_chat_members)\n';
    code += 'async def handle_new_member(message: types.Message):\n';
    code += '    """\n';
    code += '    Обработчик новых участников в группе\n';
    code += '    """\n';
    code += '    chat_id = message.chat.id\n';
    code += '    \n';
    code += '    # Проверяем, является ли группа подключенной\n';
    code += '    group_name = None\n';
    code += '    for name, config in CONNECTED_GROUPS.items():\n';
    code += '        if config.get("id") and str(config["id"]) == str(chat_id):\n';
    code += '            group_name = name\n';
    code += '            break\n';
    code += '    \n';
    code += '    if group_name:\n';
    code += '        for new_member in message.new_chat_members:\n';
    code += '            username = new_member.username or new_member.first_name or "Новый участник"\n';
    code += '            logging.info(f"👋 Новый участник в группе {group_name}: @{username}")\n';
    code += '            \n';
    code += '            # Приветственное сообщение (опционально)\n';
    code += '            # await message.answer(f"Добро пожаловать в группу, @{username}!")\n';
    code += '    \n';
    code += '  }
  return code;
}