export function navigateaftersave(code: string) {
    code += '        # Переходим к следующему узлу если указан\n';
    code += '        if next_node_id:\n';
    code += '            try:\n';
    code += '                logging.info(f"🚀 Переходим к следующему узлу: {next_node_id}")\n';
    code += '                \n';
    code += '                # Проверяем, является ли это командой\n';
    code += '                if next_node_id == "profile_command":\n';
    code += '                    logging.info("Переход к команде /profile")\n';
    code += '                    # Проверяем существование profile_handler перед вызовом\n';
    code += '                    profile_func = globals().get("profile_handler")\n';
    code += '                    if profile_func:\n';
    code += '                        await profile_func(message)\n';
    code += '                    else:\n';
    code += '                        logging.warning("profile_handler не найден, пропускаем вызов")\n';
    code += '                        await message.answer("Команда /profile не найдена")\n';
    code += '                else:\n';
    code += '                    # Создаем фиктивный callback для навигации к обычному узлу\n';
    code += '                    import types as aiogram_types\n';
    code += '                    fake_callback = aiogram_types.SimpleNamespace(\n';
    code += '                        id="conditional_nav",\n';
    code += '                        from_user=message.from_user,\n';
    code += '                        chat_instance="",\n';
    code += '                        data=next_node_id,\n';
    code += '                        message=message,\n';
    code += '                        answer=lambda text="", show_alert=False: asyncio.sleep(0)\n';
    code += '                    )\n';
    code += '                    \n';
    return code;
}
