/**
 * @fileoverview Схема узла бота
 * @module shared/schema/tables/node-schema
 */

import { z } from "zod";
import { buttonSchema } from "./button-schema";

/** Схема узла бота */
export const nodeSchema = z.object({
  /** Уникальный идентификатор узла */
  id: z.string(),
  /** Тип узла */
  type: z.enum(['start', 'message', 'command', 'sticker', 'voice', 'animation', 'location', 'contact', 'pin_message', 'unpin_message', 'delete_message', 'ban_user', 'unban_user', 'mute_user', 'unmute_user', 'kick_user', 'promote_user', 'demote_user', 'admin_rights', 'photo', 'video', 'audio', 'document', 'keyboard', 'input', 'condition', 'broadcast', 'client_auth']),
  /** Позиция узла на холсте */
  position: z.object({
    /** Координата X */
    x: z.number(),
    /** Координата Y */
    y: z.number(),
  }),
  /** Данные узла */
  data: z.object({
    command: z.string().optional(),
    description: z.string().optional(),
    messageText: z.string().optional(),
    imageUrl: z.string().optional(),
    videoUrl: z.string().optional(),
    audioUrl: z.string().optional(),
    documentUrl: z.string().optional(),
    documentName: z.string().optional(),
    mediaCaption: z.string().optional(),
    keyboardType: z.enum(['reply', 'inline', 'none']).default('none'),
    buttons: z.array(buttonSchema).default([]),
    keyboardLayout: z.object({
      rows: z.array(z.object({
        buttonIds: z.array(z.string()),
      })).default([]),
      columns: z.number().min(1).max(6).default(2),
      autoLayout: z.boolean().default(true),
    }).optional(),
    oneTimeKeyboard: z.boolean().default(false),
    resizeKeyboard: z.boolean().default(true),
    markdown: z.boolean().default(false),
    formatMode: z.enum(['html', 'markdown', 'none']).default('none'),
    synonyms: z.array(z.string()).default([]),
    isPrivateOnly: z.boolean().default(false),
    adminOnly: z.boolean().default(false),
    requiresAuth: z.boolean().default(false),
    showInMenu: z.boolean().default(true),
    commandTimeout: z.number().optional(),
    cooldownTime: z.number().optional(),
    maxUsagesPerDay: z.number().optional(),
    enableStatistics: z.boolean().default(true),
    customParameters: z.array(z.string()).default([]),
    targetMessageId: z.string().optional(),
    messageIdSource: z.enum(['manual', 'variable', 'last_message']).default('last_message'),
    variableName: z.string().optional(),
    disableNotification: z.boolean().default(false),
    targetUserId: z.string().optional(),
    userIdSource: z.enum(['manual', 'variable', 'last_message']).default('last_message'),
    userVariableName: z.string().optional(),
    targetGroupId: z.string().optional(),
    stickerUrl: z.string().optional(),
    stickerFileId: z.string().optional(),
    voiceUrl: z.string().optional(),
    animationUrl: z.string().optional(),
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    title: z.string().optional(),
    address: z.string().optional(),
    foursquareId: z.string().optional(),
    foursquareType: z.string().optional(),
    mapService: z.enum(['yandex', 'google', '2gis', 'custom']).default('custom'),
    yandexMapUrl: z.string().optional(),
    googleMapUrl: z.string().optional(),
    gisMapUrl: z.string().optional(),
    mapZoom: z.number().min(1).max(20).default(15),
    showDirections: z.boolean().default(false),
    generateMapPreview: z.boolean().default(true),
    phoneNumber: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    userId: z.number().optional(),
    vcard: z.string().optional(),
    question: z.string().optional(),
    options: z.array(z.string()).default([]),
    allowsMultipleAnswers: z.boolean().default(false),
    anonymousVoting: z.boolean().default(true),
    emoji: z.string().optional(),
    mediaDuration: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
    performer: z.string().optional(),
    fileSize: z.number().optional(),
    filename: z.string().optional(),
    inputType: z.enum(['text', 'number', 'email', 'phone', 'photo', 'video', 'audio', 'document', 'location', 'contact', 'any']).default('text'),
    responseType: z.enum(['text', 'buttons']).default('text'),
    responseOptions: z.array(z.object({
      id: z.string(),
      text: z.string(),
      value: z.string().optional(),
      action: z.enum(['goto', 'command', 'url']).default('goto'),
      target: z.string().optional(),
      url: z.string().optional()
    })).default([]),
    allowMultipleSelection: z.boolean().default(false),
    multiSelectVariable: z.string().optional(),
    continueButtonText: z.string().optional(),
    continueButtonTarget: z.string().optional(),
    inputVariable: z.string().optional(),
    inputPrompt: z.string().optional(),
    inputValidation: z.string().optional(),
    inputRequired: z.boolean().default(true),
    inputTimeout: z.number().optional(),
    inputRetryMessage: z.string().optional(),
    inputSuccessMessage: z.string().optional(),
    enableConditionalMessages: z.boolean().default(false),
    conditionalMessages: z.array(z.object({
      id: z.string(),
      condition: z.enum(['user_data_exists', 'user_data_equals', 'user_data_not_exists', 'user_data_contains', 'first_time', 'returning_user']).default('user_data_exists'),
      variableName: z.string().optional(),
      variableNames: z.array(z.string()).default([]),
      logicOperator: z.enum(['AND', 'OR']).default('AND'),
      expectedValue: z.string().optional(),
      messageText: z.string(),
      formatMode: z.enum(['text', 'markdown', 'html']).default('text'),
      keyboardType: z.enum(['reply', 'inline', 'none']).default('none'),
      buttons: z.array(buttonSchema).default([]),
      resizeKeyboard: z.boolean().default(true).optional(),
      oneTimeKeyboard: z.boolean().default(false).optional(),
      collectUserInput: z.boolean().default(false),
      enableTextInput: z.boolean().default(false),
      enablePhotoInput: z.boolean().default(false),
      enableVideoInput: z.boolean().default(false),
      enableAudioInput: z.boolean().default(false),
      enableDocumentInput: z.boolean().default(false),
      inputVariable: z.string().optional(),
      photoInputVariable: z.string().optional(),
      videoInputVariable: z.string().optional(),
      audioInputVariable: z.string().optional(),
      documentInputVariable: z.string().optional(),
      waitForTextInput: z.boolean().default(false),
      textInputVariable: z.string().optional(),
      nextNodeAfterInput: z.string().optional(),
      priority: z.number().default(0)
    })).default([]),
    fallbackMessage: z.string().optional(),
    saveToDatabase: z.boolean().default(false),
    allowSkip: z.boolean().default(false),
    collectUserInput: z.boolean().default(false),
    inputTargetNodeId: z.string().optional(),
    inputButtonType: z.enum(['inline', 'reply']).default('inline'),
    enableAutoTransition: z.boolean().default(false),
    autoTransitionTo: z.string().optional(),
    minLength: z.number().optional(),
    maxLength: z.number().optional(),
    placeholder: z.string().optional(),
    defaultValue: z.string().optional(),
    appendVariable: z.boolean().default(false),
    variableFilters: z.record(z.string()).default({}),
    enableUserActions: z.boolean().default(false),
    actionTrigger: z.enum(['join', 'leave', 'message', 'button_click', 'custom']).optional(),
    triggerText: z.string().optional(),
    userActionType: z.enum(['message', 'command', 'button', 'media']).optional(),
    actionTag: z.string().optional(),
    actionMessage: z.string().optional(),
    silentAction: z.boolean().default(false),
    mimeType: z.string().optional(),
    stickerSetName: z.string().optional(),
    fileName: z.string().optional(),
    city: z.string().optional(),
    country: z.string().optional(),
    enableTextInput: z.boolean().optional(),
    enablePhotoInput: z.boolean().optional(),
    enableVideoInput: z.boolean().optional(),
    enableAudioInput: z.boolean().optional(),
    enableDocumentInput: z.boolean().optional(),
    photoInputVariable: z.string().optional(),
    videoInputVariable: z.string().optional(),
    audioInputVariable: z.string().optional(),
    documentInputVariable: z.string().optional(),
    name: z.string().optional(),
    label: z.string().optional(),
    checkmarkSymbol: z.string().optional(),
    multiSelectCheckmark: z.string().optional(),
    duration: z.number().optional(),
    muteDuration: z.number().optional(),
    reason: z.string().optional(),
    canChangeInfo: z.boolean().default(false),
    canDeleteMessages: z.boolean().default(false),
    canBanUsers: z.boolean().default(false),
    canInviteUsers: z.boolean().default(false),
    canPinMessages: z.boolean().default(false),
    canAddAdmins: z.boolean().default(false),
    canRestrictMembers: z.boolean().default(false),
    canPromoteMembers: z.boolean().default(false),
    canManageVideoChats: z.boolean().default(false),
    canManageTopics: z.boolean().default(false),
    isAnonymous: z.boolean().default(false),
    canSendMessages: z.boolean().default(true),
    canSendMediaMessages: z.boolean().default(true),
    canSendPolls: z.boolean().default(true),
    canSendOtherMessages: z.boolean().default(true),
    canAddWebPagePreviews: z.boolean().default(true),
    canChangeGroupInfo: z.boolean().default(true),
    canInviteUsers2: z.boolean().default(true),
    canPinMessages2: z.boolean().default(true),
    untilDate: z.number().optional(),
    adminTargetUserId: z.string().optional(),
    adminUserIdSource: z.enum(['manual', 'variable', 'last_message']).default('last_message'),
    adminUserVariableName: z.string().optional(),
    can_manage_chat: z.boolean().default(false),
    can_post_messages: z.boolean().default(false),
    can_edit_messages: z.boolean().default(false),
    can_delete_messages: z.boolean().default(false),
    can_post_stories: z.boolean().default(false),
    can_edit_stories: z.boolean().default(false),
    can_delete_stories: z.boolean().default(false),
    can_manage_video_chats: z.boolean().default(false),
    can_restrict_members: z.boolean().default(false),
    can_promote_members: z.boolean().default(false),
    can_change_info: z.boolean().default(false),
    can_invite_users: z.boolean().default(false),
    can_pin_messages: z.boolean().default(false),
    can_manage_topics: z.boolean().default(false),
    is_anonymous: z.boolean().default(false),
    adminChatId: z.string().optional(),
    adminChatIdSource: z.enum(['manual', 'variable', 'current_chat']).default('current_chat'),
    adminChatVariableName: z.string().optional(),
    attachedMedia: z.array(z.string()).default([]),
    text: z.string().optional(),
    action: z.string().optional(),
    waitForTextInput: z.boolean().optional(),
    idSourceType: z.enum(['user_ids', 'bot_users', 'both']).default('bot_users').optional(),
    broadcastApiType: z.enum(['bot', 'client']).default('bot').optional(),
    broadcastTargetNode: z.string().optional(),
    enableBroadcast: z.boolean().default(false).optional(),
    enableConfirmation: z.boolean().default(false).optional(),
    confirmationText: z.string().optional(),
    successMessage: z.string().optional(),
    errorMessage: z.string().optional(),
    sessionName: z.string().default('user_session').optional(),
    sessionCreated: z.boolean().default(false).optional(),
  }),
});

/** Тип узла бота */
export type Node = z.infer<typeof nodeSchema>;
