import { Node } from '@shared/schema';
import { generateUniversalVariableReplacement } from '../database/generateUniversalVariableReplacement';
import { createSafeFunctionName } from '../format/createSafeFunctionName';
import { formatTextForPython } from '../format/formatTextForPython';
import { generateAdminRightsToggleHandlers } from './generateAdminRightsToggleHandlers';

export function generateAdminRightsHandler(node: Node): string {
  let code = `\n# Interactive Admin Rights Handler for ${node.id}\n`;

  const safeFunctionName = createSafeFunctionName(node.id);
  const messageText = node.data.messageText || "⚙️ Управление правами администратора";
  const formattedText = formatTextForPython(messageText);
  const command = node.data.command?.replace('/', '') || 'admin_rights';

  // Создаем основной command handler с автоматическим определением участника
  code += `@dp.message(Command("${command}"))\n`;
  code += `async def ${safeFunctionName}_command_handler(message: types.Message, bot):\n`;
  code += `    """\n`;
  code += `    Основной обработчик команды ${node.data.command || '/admin_rights'}\n`;
  code += `    Автоматически определяет целевого пользователя из контекста\n`;
  code += `    """\n`;
  code += `    user_id = message.from_user.id\n`;
  code += `    chat_id = message.chat.id\n`;
  code += `    target_user_id = None\n`;
  code += `    \n`;
  code += `    logging.info(f"Команда admin_rights вызвана пользователем {user_id} в чате {chat_id}")\n`;
  code += `    \n`;
  code += `    # Проверяем права вызывающего пользователя\n`;
  code += `    try:\n`;
  code += `        current_user_member = await bot.get_chat_member(chat_id, user_id)\n`;
  code += `        if current_user_member.status not in ['administrator', 'creator']:\n`;
  code += `            await message.answer("❌ У вас нет прав администратора для использования этой команды")\n`;
  code += `            return\n`;
  code += `        \n`;
  code += `        if current_user_member.status != 'creator' and not getattr(current_user_member, 'can_promote_members', False):\n`;
  code += `            await message.answer("❌ У вас нет права на управление правами других администраторов")\n`;
  code += `            return\n`;
  code += `    except Exception as e:\n`;
  code += `        await message.answer(f"❌ Ошибка при проверке ваших прав: {e}")\n`;
  code += `        return\n`;
  code += `    \n`;
  code += `    # Автоматическое определение целевого пользователя\n`;
  code += `    \n`;
  code += `    # 1. Проверяем, есть ли ответ на сообщение\n`;
  code += `    if message.reply_to_message and message.reply_to_message.from_user:\n`;
  code += `        target_user_id = message.reply_to_message.from_user.id\n`;
  code += `        logging.info(f"Целевой пользователь определен из ответа на сообщение: {target_user_id}")\n`;
  code += `    \n`;
  code += `    # 2. Проверяем, есть ли упоминание в тексте (@username или прямое упоминание)\n`;
  code += `    elif message.entities:\n`;
  code += `        for entity in message.entities:\n`;
  code += `            # Приоритет - прямое упоминание с объектом пользователя\n`;
  code += `            if entity.type == "text_mention" and hasattr(entity, 'user'):\n`;
  code += `                target_user_id = entity.user.id\n`;
  code += `                logging.info(f"Целевой пользователь определен из прямого упоминания: {target_user_id}")\n`;
  code += `                break\n`;
  code += `            elif entity.type == "mention":\n`;
  code += `                # Извлекаем username из упоминания\n`;
  code += `                username = message.text[entity.offset+1:entity.offset+entity.length]  # +1 чтобы убрать @\n`;
  code += `                try:\n`;
  code += `                    # Пытаемся найти пользователя по username через участников чата\n`;
  code += `                    chat_admins = await bot.get_chat_administrators(chat_id)\n`;
  code += `                    for member in chat_admins:\n`;
  code += `                        if member.user.username and member.user.username.lower() == username.lower():\n`;
  code += `                            target_user_id = member.user.id\n`;
  code += `                            logging.info(f"Целевой пользователь определен из упоминания @{username}: {target_user_id}")\n`;
  code += `                            break\n`;
  code += `                except Exception as e:\n`;
  code += `                    logging.warning(f"Не удалось найти пользователя @{username}: {e}")\n`;
  code += `                break\n`;
  code += `    \n`;
  code += `    # 3. Проверяем, есть ли ID в тексте команды\n`;
  code += `    if target_user_id is None:\n`;
  code += `        # Ищем числовой ID в аргументах команды\n`;
  code += `        import re\n`;
  code += `        # Извлекаем все числа из текста команды (исключая сам command)\n`;
  code += `        command_text = message.text or ""\n`;
  code += `        numbers = re.findall(r'\\b\\d{6,}\\b', command_text)  # ID обычно 6+ цифр\n`;
  code += `        \n`;
  code += `        for number_str in numbers:\n`;
  code += `            try:\n`;
  code += `                potential_user_id = int(number_str)\n`;
  code += `                # Проверяем, что это валидный пользователь в чате\n`;
  code += `                try:\n`;
  code += `                    member_check = await bot.get_chat_member(chat_id, potential_user_id)\n`;
  code += `                    target_user_id = potential_user_id\n`;
  code += `                    logging.info(f"Целевой пользователь определен из ID в команде: {target_user_id}")\n`;
  code += `                    break\n`;
  code += `                except Exception:\n`;
  code += `                    logging.debug(f"ID {potential_user_id} не найден в чате, попробуем следующий")\n`;
  code += `                    continue\n`;
  code += `            except ValueError:\n`;
  code += `                continue\n`;
  code += `    \n`;
  code += `    # Если целевой пользователь не определен, показываем инструкцию\n`;
  code += `    if target_user_id is None:\n`;
  code += `        await message.answer(\n`;
  code += `            "❓ Укажите пользователя для управления правами:\\n"\n`;
  code += `            "• Ответьте на сообщение пользователя\\n"\n`;
  code += `            "• Упомяните пользователя: /admin_rights @username\\n"\n`;
  code += `            "• Укажите ID: /admin_rights 123456789"\n`;
  code += `        )\n`;
  code += `        return\n`;
  code += `    \n`;
  code += `    # Проверяем, что целевой пользователь является администратором\n`;
  code += `    try:\n`;
  code += `        target_member = await bot.get_chat_member(chat_id, target_user_id)\n`;
  code += `        if target_member.status not in ['administrator', 'creator']:\n`;
  code += `            await message.answer("❌ Указанный пользователь не является администратором")\n`;
  code += `            return\n`;
  code += `    except Exception as e:\n`;
  code += `        await message.answer(f"❌ Не удалось проверить пользователя: {e}")\n`;
  code += `        return\n`;
  code += `    \n`;
  code += `    # Создаем и отправляем интерактивную клавиатуру\n`;
  code += `    keyboard = await create_admin_rights_keyboard_${safeFunctionName}(bot, chat_id, target_user_id)\n`;
  code += `    text = ${formattedText}\n`;
  const universalVarCodeLines1: string[] = [];
  generateUniversalVariableReplacement(universalVarCodeLines1, '    ');
  code += universalVarCodeLines1.join('\n');
  code += `    \n`;
  code += `    await message.answer(text, reply_markup=keyboard)\n`;
  code += `\n`;

  // Создаем функцию для получения текущих прав администратора
  code += `async def get_admin_rights_${safeFunctionName}(bot, chat_id, target_user_id):\n`;
  code += `    """\n`;
  code += `    Получает текущие права администратора пользователя в чате\n`;
  code += `    """\n`;
  code += `    try:\n`;
  code += `        member = await bot.get_chat_member(chat_id, target_user_id)\n`;
  code += `        if hasattr(member, 'status') and member.status in ['administrator', 'creator']:\n`;
  code += `            # Возвращаем основные права администратора включая управление историями\n`;
  code += `            return {\n`;
  code += `                'can_change_info': getattr(member, 'can_change_info', False),\n`;
  code += `                'can_delete_messages': getattr(member, 'can_delete_messages', False),\n`;
  code += `                'can_restrict_members': getattr(member, 'can_restrict_members', False),\n`;
  code += `                'can_invite_users': getattr(member, 'can_invite_users', False),\n`;
  code += `                'can_pin_messages': getattr(member, 'can_pin_messages', False),\n`;
  code += `                'can_manage_video_chats': getattr(member, 'can_manage_video_chats', False),\n`;
  code += `                'can_post_stories': getattr(member, 'can_post_stories', False),\n`;
  code += `                'can_edit_stories': getattr(member, 'can_edit_stories', False),\n`;
  code += `                'can_delete_stories': getattr(member, 'can_delete_stories', False),\n`;
  code += `                'is_anonymous': getattr(member, 'is_anonymous', False),\n`;
  code += `                'can_promote_members': getattr(member, 'can_promote_members', False)\n`;
  code += `            }\n`;
  code += `        else:\n`;
  code += `            # Пользователь не является администратором\n`;
  code += `            return None\n`;
  code += `    except Exception as e:\n`;
  code += `        logging.error(f"Ошибка при получении прав администратора: {e}")\n`;
  code += `        return None\n`;
  code += `\n`;

  // Создаем функцию для генерации интерактивной клавиатуры
  code += `async def create_admin_rights_keyboard_${safeFunctionName}(bot, chat_id, target_user_id, node_id="${node.id}"):\n`;
  code += `    """\n`;
  code += `    Создает интерактивную клавиатуру с кнопками-переключателями прав\n`;
  code += `    """\n`;
  code += `    # Получаем текущие права\n`;
  code += `    current_rights = await get_admin_rights_${safeFunctionName}(bot, chat_id, target_user_id)\n`;
  code += `    \n`;
  code += `    builder = InlineKeyboardBuilder()\n`;
  code += `    \n`;
  code += `    if current_rights is None:\n`;
  code += `        # Пользователь не администратор\n`;
  code += `        builder.add(InlineKeyboardButton(text="❌ Пользователь не является администратором", callback_data="no_admin"))\n`;
  code += `        return builder.as_markup()\n`;
  code += `    \n`;
  code += `    # Список основных прав администратора включая управление историями\n`;
  code += `    admin_rights_list = [\n`;
  code += `        ('can_change_info', '🏷️ Изменение профиля'),\n`;
  code += `        ('can_delete_messages', '🗑️ Удаление сообщений'),\n`;
  code += `        ('can_restrict_members', '🚫 Блокировка участников'),\n`;
  code += `        ('can_invite_users', '📨 Приглашение участников'),\n`;
  code += `        ('can_pin_messages', '📌 Закрепление сообщений'),\n`;
  code += `        ('can_manage_video_chats', '🎥 Управление видеочатами'),\n`;
  code += `        ('can_post_stories', '📰 Публикация историй'),\n`;
  code += `        ('can_edit_stories', '✏️ Редактирование историй'),\n`;
  code += `        ('can_delete_stories', '🗑️ Удаление историй'),\n`;
  code += `        ('is_anonymous', '🔒 Анонимность'),\n`;
  code += `        ('can_promote_members', '👑 Назначение администраторов')\n`;
  code += `    ]\n`;
  code += `    \n`;
  code += `    # Создаем кнопки с индикаторами состояния\n`;
  code += `    for right_key, right_name in admin_rights_list:\n`;
  code += `        is_enabled = current_rights.get(right_key, False)\n`;
  code += `        indicator = "✅" if is_enabled else "❌"\n`;
  code += `        button_text = f"{indicator} {right_name}"\n`;
  code += `        # Укорачиваем callback_data для соблюдения лимита Telegram (64 байта)\n`;
  code += `        short_node_id = str(hash(node_id))[-6:]  # Берем последние 6 символов хэша\n`;
  code += `        callback_data = f"tr_{right_key[:12]}_{target_user_id}_{short_node_id}"\n`;
  code += `        builder.add(InlineKeyboardButton(text=button_text, callback_data=callback_data))\n`;
  code += `    \n`;
  code += `    # Кнопка для обновления состояния (с коротким callback_data)\n`;
  code += `    short_node_id = str(hash(node_id))[-6:]  # Берем последние 6 символов хэша\n`;
  code += `    builder.add(InlineKeyboardButton(text="🔄 Обновить", callback_data=f"ref_{target_user_id}_{short_node_id}"))\n`;
  code += `    \n`;
  code += `    builder.adjust(1)  # Располагаем кнопки в одну колонку для лучшей читаемости\n`;
  code += `    return builder.as_markup()\n`;
  code += `\n`;

  // Главный callback обработчик для узла admin_rights
  code += `@dp.callback_query(lambda c: c.data == "${node.id}")\n`;
  code += `async def handle_callback_${safeFunctionName}(callback_query: types.CallbackQuery, bot):\n`;
  code += `    """\n`;
  code += `    Обработчик callback для узла admin_rights: ${node.id}\n`;
  code += `    Отображает интерактивную клавиатуру для управления правами администратора\n`;
  code += `    """\n`;
  code += `    await callback_query.answer()\n`;
  code += `    user_id = callback_query.from_user.id\n`;
  code += `    chat_id = callback_query.message.chat.id\n`;
  code += `    \n`;
  code += `    logging.info(f"Обработка callback admin_rights от пользователя {user_id} в чате {chat_id}")\n`;
  code += `    \n`;
  code += `    # Проверяем права БОТА (не пользователя) на управление правами администраторов\n`;
  code += `    try:\n`;
  code += `        bot_member = await bot.get_chat_member(chat_id, bot.id)\n`;
  code += `        if bot_member.status not in ['administrator', 'creator']:\n`;
  code += `            await safe_edit_or_send(callback_query, "❌ Бот не является администратором этой группы")\n`;
  code += `            return\n`;
  code += `        \n`;
  code += `        # Проверяем, может ли бот управлять правами других администраторов\n`;
  code += `        if bot_member.status != 'creator' and not getattr(bot_member, 'can_promote_members', False):\n`;
  code += `            await safe_edit_or_send(callback_query, "❌ У бота нет права на управление правами администраторов")\n`;
  code += `            return\n`;
  code += `    except Exception as e:\n`;
  code += `        logging.error(f"Ошибка при проверке прав администратора: {e}")\n`;
  code += `        await safe_edit_or_send(callback_query, "❌ Не удалось проверить права администратора. Попробуйте позже.")\n`;
  code += `        return\n`;
  code += `    \n`;
  code += `    # Получаем target_user_id (пользователя, чьи права будем менять)\n`;
  code += `    # В данном случае, мы будем управлять правами пользователя, который вызвал команду\n`;
  code += `    # Но это можно изменить для работы с replied сообщениями\n`;
  code += `    target_user_id = user_id  # По умолчанию управляем своими правами\n`;
  code += `    \n`;
  code += `    # Если это ответ на сообщение, берем пользователя из ответа\n`;
  code += `    if hasattr(callback_query.message, 'reply_to_message') and callback_query.message.reply_to_message:\n`;
  code += `        target_user_id = callback_query.message.reply_to_message.from_user.id\n`;
  code += `        logging.info(f"Управляем правами пользователя {target_user_id} из ответа на сообщение")\n`;
  code += `    \n`;
  code += `    # Текст сообщения\n`;
  code += `    text = ${formattedText}\n`;

  // Добавляем универсальную замену переменных
  const universalVarCodeLines2: string[] = [];
  generateUniversalVariableReplacement(universalVarCodeLines2, '    ');
  code += universalVarCodeLines2.join('\n');
  code += `    \n`;
  code += `    # Создаем интерактивную клавиатуру\n`;
  code += `    keyboard = await create_admin_rights_keyboard_${safeFunctionName}(bot, chat_id, target_user_id)\n`;
  code += `    \n`;
  code += `    # Отправляем/обновляем сообщение с клавиатурой\n`;
  code += `    try:\n`;
  code += `        # Пробуем отредактировать сообщение (работает для inline callbacks)\n`;
  code += `        await safe_edit_or_send(callback_query, text, reply_markup=keyboard)\n`;
  code += `    except Exception as e:\n`;
  code += `        # Если не удалось отредактировать (например, для text commands), отправляем новое сообщение\n`;
  code += `        logging.info(f"Отправляем новое сообщение admin_rights: {e}")\n`;
  code += `        await callback_query.message.answer(text, reply_markup=keyboard)\n`;
  code += `\n`;

  // Добавляем callback обработчики для переключения прав
  code += generateAdminRightsToggleHandlers(node);

  return code;
}
