import { useState, useCallback, useEffect, useRef } from 'react';
import { Node, Connection, Button, BotData } from '@shared/schema';
import { applyTemplateLayout } from '@/utils/hierarchical-layout';
import { generateAutoTransitionConnections } from '@/utils/auto-transition-connections';
import { useLocalStorage } from './utils/use-local-storage';
import { useDebouncedCallback } from './utils/use-debounce';

interface HistoryState {
  nodes: Node[];
  connections: Connection[];
}

interface UseBotEditorOptions {
  initialData?: BotData;
  maxHistorySize?: number;
  autoSaveDelay?: number;
  enableClipboard?: boolean;
}

/**
 * Refactored bot editor hook with improved separation of concerns
 * Uses new utility hooks for better maintainability
 */
export function useBotEditorRefactored(options: UseBotEditorOptions = {}) {
  const {
    initialData,
    maxHistorySize = 50,
    autoSaveDelay = 300,
    enableClipboard = true,
  } = options;

  // Core state
  const [nodes, setNodes] = useState<Node[]>(initialData?.nodes || []);
  const [connections, setConnections] = useState<Connection[]>(initialData?.connections || []);
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const [isNodeBeingDragged, setIsNodeBeingDragged] = useState(false);

  // History management
  const [history, setHistory] = useState<HistoryState[]>([]);
  const [historyIndex, setHistoryIndex] = useState(-1);
  const isRedoUndoActionRef = useRef(false);

  // Clipboard storage (if enabled)
  interface ClipboardData {
    nodes: Node[];
    connections: Connection[];
    timestamp: number;
    projectType: string;
  }

  const [clipboardData, setClipboardData] = useLocalStorage<ClipboardData | null>(
    'bot-clipboard',
    null,
    { initializeWithValue: enableClipboard }
  );

  const selectedNode = nodes.find(node => node.id === selectedNodeId) || null;

  // Debounced history save to prevent excessive saves during rapid changes
  const debouncedSaveToHistory = useDebouncedCallback(() => {
    if (isRedoUndoActionRef.current) return;
    
    const currentState: HistoryState = {
      nodes: JSON.parse(JSON.stringify(nodes)),
      connections: JSON.parse(JSON.stringify(connections))
    };
    
    setHistory(prev => {
      const newHistory = prev.slice(0, historyIndex + 1);
      newHistory.push(currentState);
      
      if (newHistory.length > maxHistorySize) {
        return newHistory.slice(-maxHistorySize);
      }
      
      return newHistory;
    });
    
    setHistoryIndex(prev => Math.min(prev + 1, maxHistorySize - 1));
  }, autoSaveDelay, [nodes, connections, historyIndex]);

  // Initialize history
  useEffect(() => {
    if (history.length === 0 && (nodes.length > 0 || connections.length > 0)) {
      const initialState: HistoryState = {
        nodes: JSON.parse(JSON.stringify(nodes)),
        connections: JSON.parse(JSON.stringify(connections))
      };
      setHistory([initialState]);
      setHistoryIndex(0);
    }
  }, [nodes, connections, history.length]);

  // Auto-save to history on changes
  useEffect(() => {
    if (!isRedoUndoActionRef.current && history.length > 0) {
      debouncedSaveToHistory();
    }
  }, [nodes, connections, debouncedSaveToHistory, history.length]);

  // Auto-generate connections
  useEffect(() => {
    if (!isRedoUndoActionRef.current && nodes.length > 0) {
      setConnections((prevConnections: Connection[]) => {
        const updatedConnections = generateAutoTransitionConnections(nodes as Node[], prevConnections);
        
        if (updatedConnections.length !== prevConnections.length) {
          console.log('🔗 Автопереходы обновлены:', updatedConnections.filter((c: Connection) => c.isAutoGenerated));
          return updatedConnections;
        }
        
        const hasChanges = updatedConnections.some((conn: Connection, index: number) => {
          const prevConn = prevConnections[index];
          return !prevConn || conn.id !== prevConn.id || 
                 conn.source !== prevConn.source || 
                 conn.target !== prevConn.target ||
                 conn.isAutoGenerated !== prevConn.isAutoGenerated;
        });
        
        return hasChanges ? updatedConnections : prevConnections;
      });
    }
  }, [nodes]);

  // History operations
  const undo = useCallback(() => {
    if (historyIndex > 0) {
      const prevIndex = historyIndex - 1;
      const prevState = history[prevIndex];
      
      isRedoUndoActionRef.current = true;
      setHistoryIndex(prevIndex);
      setSelectedNodeId(null);
      
      setTimeout(() => {
        setNodes(prevState.nodes);
        setConnections(prevState.connections);
        setTimeout(() => { isRedoUndoActionRef.current = false; }, 100);
      }, 0);
    }
  }, [history, historyIndex]);

  const redo = useCallback(() => {
    if (historyIndex < history.length - 1) {
      const nextIndex = historyIndex + 1;
      const nextState = history[nextIndex];
      
      isRedoUndoActionRef.current = true;
      setHistoryIndex(nextIndex);
      setSelectedNodeId(null);
      
      setTimeout(() => {
        setNodes(nextState.nodes);
        setConnections(nextState.connections);
        setTimeout(() => { isRedoUndoActionRef.current = false; }, 100);
      }, 0);
    }
  }, [history, historyIndex]);

  const canUndo = historyIndex > 0;
  const canRedo = historyIndex < history.length - 1;

  // Node operations
  const addNode = useCallback((node: Node) => {
    setNodes(prev => [...prev, node]);
  }, []);

  const updateNode = useCallback((nodeId: string, updates: Partial<Node>) => {
    setNodes((prev: Node[]) => prev.map((node: Node) => 
      node.id === nodeId ? { ...node, ...updates } as Node : node
    ));
  }, []);

  const deleteNode = useCallback((nodeId: string) => {
    setNodes((prev: Node[]) => prev.filter((node: Node) => node.id !== nodeId));
    setConnections((prev: Connection[]) => prev.filter((conn: Connection) => 
      conn.source !== nodeId && conn.target !== nodeId
    ));
    if (selectedNodeId === nodeId) {
      setSelectedNodeId(null);
    }
  }, [selectedNodeId]);

  const duplicateNode = useCallback((nodeId: string) => {
    const nodeToDuplicate = nodes.find((node: Node) => node.id === nodeId);
    if (!nodeToDuplicate) return;

    const duplicatedNode: Node = {
      ...JSON.parse(JSON.stringify(nodeToDuplicate)),
      id: `${nodeId}_copy_${Date.now()}`,
      position: {
        x: nodeToDuplicate.position.x + 50,
        y: nodeToDuplicate.position.y + 50
      }
    };

    setNodes((prev: Node[]) => [...prev, duplicatedNode]);
    setSelectedNodeId(duplicatedNode.id);
  }, [nodes]);

  // Connection operations
  const addConnection = useCallback((connection: Connection) => {
    setConnections((prev: Connection[]) => [...prev, connection]);
  }, []);

  const deleteConnection = useCallback((connectionId: string) => {
    let wasDeleted = false;
    setConnections((prev: Connection[]) => {
      const connToDelete = prev.find((c: Connection) => c.id === connectionId);
      if (connToDelete?.isAutoGenerated) {
        console.warn('Попытка удалить автогенерированное соединение. Измените свойство autoTransitionTo узла.');
        return prev;
      }
      wasDeleted = true;
      return prev.filter((conn: Connection) => conn.id !== connectionId);
    });
    return wasDeleted;
  }, []);

  const updateConnection = useCallback((connectionId: string, updates: Partial<Connection>) => {
    setConnections((prev: Connection[]) => prev.map((conn: Connection) => 
      conn.id === connectionId ? { ...conn, ...updates } : conn
    ));
  }, []);

  // Node data operations
  const updateNodeData = useCallback((nodeId: string, data: Partial<Node['data']>) => {
    setNodes((prev: Node[]) => prev.map((node: Node) => 
      node.id === nodeId 
        ? { ...node, data: { ...node.data, ...data } } as Node
        : node
    ));
  }, []);

  // Button operations
  const addButton = useCallback((nodeId: string, button: Button) => {
    setNodes((prev: Node[]) => prev.map((node: Node) => 
      node.id === nodeId 
        ? { 
            ...node, 
            data: { 
              ...node.data, 
              buttons: [...(node.data.buttons || []), button] 
            } 
          } as Node
        : node
    ));
  }, []);

  const updateButton = useCallback((nodeId: string, buttonId: string, updates: Partial<Button>) => {
    setNodes((prev: Node[]) => prev.map((node: Node) => 
      node.id === nodeId 
        ? { 
            ...node, 
            data: { 
              ...node.data, 
              buttons: (node.data.buttons || []).map((btn: Button) => 
                btn.id === buttonId ? { ...btn, ...updates } : btn
              )
            } 
          } as Node
        : node
    ));
  }, []);

  const deleteButton = useCallback((nodeId: string, buttonId: string) => {
    setNodes((prev: Node[]) => prev.map((node: Node) => 
      node.id === nodeId 
        ? { 
            ...node, 
            data: { 
              ...node.data, 
              buttons: (node.data.buttons || []).filter((btn: Button) => btn.id !== buttonId)
            } 
          } as Node
        : node
    ));
  }, []);

  // Bulk operations
  const updateNodes = useCallback((newNodes: Node[]) => {
    setNodes(newNodes);
  }, []);

  const duplicateNodes = useCallback((nodeIds: string[]) => {
    const nodesToDuplicate = nodes.filter(node => nodeIds.includes(node.id));
    if (nodesToDuplicate.length === 0) return;

    const idMapping: { [oldId: string]: string } = {};
    const duplicatedNodes: Node[] = [];

    nodesToDuplicate.forEach(node => {
      const newId = `${node.id}_copy_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
      idMapping[node.id] = newId;

      const duplicatedNode: Node = {
        ...JSON.parse(JSON.stringify(node)),
        id: newId,
        position: {
          x: node.position.x + 50,
          y: node.position.y + 50
        }
      };

      duplicatedNodes.push(duplicatedNode);
    });

    const duplicatedConnections: Connection[] = [];
    connections.forEach(connection => {
      const sourceId = idMapping[connection.source];
      const targetId = idMapping[connection.target];
      
      if (sourceId && targetId) {
        const duplicatedConnection: Connection = {
          ...JSON.parse(JSON.stringify(connection)),
          id: `${connection.id}_copy_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          source: sourceId,
          target: targetId
        };
        duplicatedConnections.push(duplicatedConnection);
      }
    });

    setNodes(prev => [...prev, ...duplicatedNodes]);
    setConnections(prev => [...prev, ...duplicatedConnections]);
    
    if (duplicatedNodes.length > 0) {
      setSelectedNodeId(duplicatedNodes[0].id);
    }
  }, [nodes, connections]);

  // Data normalization
  const normalizeNodeData = useCallback((node: Node): Node => {
    if (!node || !node.type) return node;

    const normalizedData = { ...node.data };

    const defaultFields = {
      buttons: [],
      messageText: '',
      keyboardType: 'none' as const,
      oneTimeKeyboard: false,
      resizeKeyboard: true,
      markdown: false,
      isPrivateOnly: false,
      adminOnly: false,
      requiresAuth: false,
      showInMenu: true,
      enableStatistics: true
    };

    for (const [key, value] of Object.entries(defaultFields)) {
      if ((normalizedData as any)[key] === undefined) {
        (normalizedData as any)[key] = value;
      }
    }

    if (node.type === 'start' || node.type === 'command') {
      if (!(normalizedData as any).command) {
        (normalizedData as any).command = node.type === 'start' ? '/start' : '/command';
      }
      if (!normalizedData.description) {
        normalizedData.description = node.type === 'start' ? 'Запустить бота' : 'Команда бота';
      }
    }

    return {
      ...node,
      data: normalizedData
    } as Node;
  }, []);

  // Bot data operations
  const setBotData = useCallback((
    botData: BotData, 
    templateName?: string, 
    nodeSizes?: Map<string, { width: number; height: number }>,
    skipLayout?: boolean
  ) => {
    const normalizedNodes: Node[] = (botData.nodes || []).map(normalizeNodeData) as Node[];
    const connectionsWithAuto = generateAutoTransitionConnections(
      normalizedNodes, 
      botData.connections || []
    );
    
    const finalNodes = skipLayout 
      ? normalizedNodes 
      : applyTemplateLayout(normalizedNodes, connectionsWithAuto, templateName, nodeSizes);
    
    setNodes(finalNodes as Node[]);
    setConnections(connectionsWithAuto);
    setSelectedNodeId(null);
  }, [normalizeNodeData]);

  const getBotData = useCallback((): BotData => ({
    nodes,
    connections
  }), [nodes, connections]);

  // Clipboard operations (if enabled)
  const copyToClipboard = useCallback((nodeIds: string[]) => {
    if (!enableClipboard) return null;

    const nodesToCopy = nodes.filter((node: Node) => nodeIds.includes(node.id));
    const connectionsToCopy = connections.filter((conn: Connection) => 
      nodeIds.includes(conn.source) && nodeIds.includes(conn.target)
    );

    const clipboardDataObj: ClipboardData = {
      nodes: nodesToCopy,
      connections: connectionsToCopy,
      timestamp: Date.now(),
      projectType: 'telegram-bot'
    };

    setClipboardData(clipboardDataObj);
    return clipboardDataObj;
  }, [nodes, connections, enableClipboard, setClipboardData]);

  const pasteFromClipboard = useCallback((offsetX: number = 100, offsetY: number = 100) => {
    if (!enableClipboard || !clipboardData) return false;

    try {
      if (!clipboardData.nodes || !Array.isArray(clipboardData.nodes) || 
          !clipboardData.timestamp || Date.now() - clipboardData.timestamp > 24 * 60 * 60 * 1000) {
        return false;
      }

      const idMapping: { [oldId: string]: string } = {};
      const pastedNodes: Node[] = [];

      clipboardData.nodes.forEach((node: Node) => {
        const newId = `${node.id}_paste_${Date.now()}_${Math.random().toString(36).substring(2, 11)}`;
        idMapping[node.id] = newId;

        const pastedNode: Node = {
          ...JSON.parse(JSON.stringify(node)),
          id: newId,
          position: {
            x: node.position.x + offsetX,
            y: node.position.y + offsetY
          }
        };

        pastedNodes.push(pastedNode);
      });

      const pastedConnections: Connection[] = [];
      clipboardData.connections.forEach((connection: Connection) => {
        const sourceId = idMapping[connection.source];
        const targetId = idMapping[connection.target];
        
        if (sourceId && targetId) {
          const pastedConnection: Connection = {
            ...JSON.parse(JSON.stringify(connection)),
            id: `${connection.id}_paste_${Date.now()}_${Math.random().toString(36).substring(2, 11)}`,
            source: sourceId,
            target: targetId
          };
          pastedConnections.push(pastedConnection);
        }
      });

      setNodes((prev: Node[]) => [...prev, ...pastedNodes]);
      setConnections((prev: Connection[]) => [...prev, ...pastedConnections]);

      if (pastedNodes.length > 0) {
        setSelectedNodeId(pastedNodes[0].id);
      }

      return true;
    } catch (error) {
      console.error('Ошибка при вставке из буфера обмена:', error);
      return false;
    }
  }, [enableClipboard, clipboardData]);

  const hasClipboardData = useCallback(() => {
    if (!enableClipboard || !clipboardData) return false;

    try {
      return !!(clipboardData.nodes && Array.isArray(clipboardData.nodes) && 
               clipboardData.nodes.length > 0 && clipboardData.timestamp &&
               Date.now() - clipboardData.timestamp <= 24 * 60 * 60 * 1000);
    } catch {
      return false;
    }
  }, [enableClipboard, clipboardData]);

  return {
    // State
    nodes,
    connections,
    selectedNode,
    selectedNodeId,
    isNodeBeingDragged,
    
    // Selection
    setSelectedNodeId,
    setIsNodeBeingDragged,
    
    // Node operations
    addNode,
    updateNode,
    deleteNode,
    duplicateNode,
    duplicateNodes,
    updateNodes,
    
    // Connection operations
    addConnection,
    deleteConnection,
    updateConnection,
    
    // Node data operations
    updateNodeData,
    addButton,
    updateButton,
    deleteButton,
    
    // Bot data operations
    setBotData,
    getBotData,
    
    // History operations
    undo,
    redo,
    canUndo,
    canRedo,
    
    // Clipboard operations (if enabled)
    ...(enableClipboard && {
      copyToClipboard,
      pasteFromClipboard,
      hasClipboardData,
    }),
  };
}