import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Ручной сайдбар публичной документации.
 * Планы (futures/, roadmaps/) намеренно не включены.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'home',
      label: 'Главная',
    },
    {
      type: 'category',
      label: 'Быстрый старт',
      collapsed: false,
      items: [
        'development/INSTALLATION',
        'development/HOW_TO_UPDATE',
        'development/TROUBLESHOOTING_RU',
        'deployment/RAILWAY_QUICK_DEPLOY',
        'deployment/VERCEL_DEPLOY',
      ],
    },
    {
      type: 'category',
      label: 'Интерфейс',
      items: [
        'interface/overview',
        'interface/editor',
        'interface/editor/canvas',
        'interface/editor/properties',
        'interface/editor/components',
        'interface/editor/projects',
        'interface/editor/sheets',
        'interface/editor/toolbar',
        'interface/bot',
        'interface/users',
        'interface/dialogs',
        'interface/files',
        'interface/code',
        'interface/terminal',
        'interface/analytics',
        {
          type: 'category',
          label: 'Таблицы',
          items: [
            'interface/tables/overview',
            'interface/tables/editing',
            'interface/tables/import-export',
            'interface/tables/system-tables',
          ],
        },
        {
          type: 'category',
          label: 'Рассылки',
          items: [
            'interface/broadcasts/overview',
            'interface/broadcasts/create',
            'interface/broadcasts/id-database',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Ноды',
      items: [
        'nodes/overview',
        'nodes/triggers/command-trigger',
        'nodes/actions/message',
        'nodes/actions/set-variable',
        'nodes/logic/condition',
        'nodes/utility/comment',
        'features/NODE_TYPES',
        'features/POSSIBLE_TRIGGERS_AND_ACTIONS',
      ],
    },
    {
      type: 'category',
      label: 'Переменные',
      items: ['variables/overview', 'variables/variable-selector'],
    },
    {
      type: 'category',
      label: 'MCP и ИИ',
      items: [
        'mcp/overview',
        'mcp/bot-builder',
        'mcp/example-simple-bot',
        'bot-json-prompt',
      ],
    },
    {
      type: 'category',
      label: 'Разработка',
      items: [
        'development/CONTRIBUTING',
        'development/adding-new-trigger',
        'development/WIKI_DOCS_GUIDE',
        'JSDOC_STANDARDS',
        'CLIENT-README',
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
    {
      type: 'category',
      label: 'База данных',
      items: [{type: 'autogenerated', dirName: 'database'}],
    },
    {
      type: 'category',
      label: 'Фичи',
      items: [
        'features/project-versioning',
        'features/incoming-callback-trigger',
        'features/realtime-collaboration',
        'features/TELEGRAM_CLIENT_API_TRIGGERS_AND_ACTIONS',
        'features/telegram-buttons-new-features',
      ],
    },
    {
      type: 'category',
      label: 'Релизы',
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
  ],
};

export default sidebars;
