import { Node } from '@shared/schema';
import { hasInlineButtons } from '../has';

/**
 * Функция для генерации кода логирования сообщений при включенной БД
 * @param userDatabaseEnabled - Включена ли база данных для логирования
 * @param projectId - ID проекта
 * @param nodes - Узлы бота
 * @returns Строка с кодом логирования сообщений, если БД включена, иначе пустая строка
 */
export function generateMessageLoggingCode(userDatabaseEnabled: boolean, projectId: number | null, nodes: Node[]): string {
  if (!userDatabaseEnabled) {
    return '';
  }

  let code = '';
  code += '# API configuration для сохранения сообщений\n';
  code += '# Определяем URL сервера автоматически\n';
  code += 'def get_api_base_url():\n';
  code += '    # Сначала пробуем получить из переменных окружения\n';
  code += '    env_url = os.getenv("API_BASE_URL", os.getenv("REPLIT_DEV_DOMAIN"))\n';
  code += '    if env_url:\n';
  code += '        # Если URL начинается с http/https, используем как есть\n';
  code += '        if env_url.startswith(("http://", "https://")):\n';
  code += '            return env_url\n';
  code += '        # Если нет, добавляем протокол\n';
  code += '        elif ":" in env_url:  # содержит порт\n';
  code += '            return f"http://{env_url}"\n';
  code += '        else:  # домен без порта\n';
  code += '            return f"https://{env_url}"\n';
  code += '    \n';
  code += '    # Пытаемся определить URL автоматически\n';
  code += '    try:\n';
  code += '        import socket\n';
  code += '        # Получаем IP-адрес машины\n';
  code += '        hostname = socket.gethostname()\n';
  code += '        local_ip = socket.gethostbyname(hostname)\n';
  code += '        \n';
  code += '        # Определяем порт из переменной окружения или используем 5000 по умолчанию\n';
  code += '        port = os.getenv("API_PORT", "5000")\n';
  code += '        \n';
  code += '        # Проверяем, является ли IP локальным\n';
  code += '        if local_ip.startswith(("127.", "192.168.", "10.", "172.")) or local_ip == "::1":\n';
  code += '            # Для локальных IP используем localhost\n';
  code += '            return f"http://localhost:{port}"\n';
  code += '        else:\n';
  code += '            # Для внешних IP используем IP-адрес\n';
  code += '            return f"http://{local_ip}:{port}"\n';
  code += '    except:\n';
  code += '        # Если не удалось определить автоматически, используем localhost с портом из переменной окружения\n';
  code += '        port = os.getenv("API_PORT", "5000")\n';
  code += '        return f"http://localhost:{port}"\n';
  code += '\n';
  code += 'API_BASE_URL = get_api_base_url()\n';
  code += 'logging.info(f"📡 API Base URL определён как: {API_BASE_URL}")\n';
  code += `PROJECT_ID = int(os.getenv("PROJECT_ID", "${projectId || 0}"))  # ID проекта в системе\n\n`;

  code += '# Функция для сохранения сообщений в базу данных через API\n';
  code += 'async def save_message_to_api(user_id: str, message_type: str, message_text: str = None, node_id: str = None, message_data: dict = None):\n';
  code += '    """Сохраняет сообщение в базу данных через API"""\n';
  code += '    try:\n';
  code += '        # Формируем полный URL для API\n';
  code += '        if API_BASE_URL.startswith("http"):\n';
  code += '            api_url = f"{API_BASE_URL}/api/projects/{PROJECT_ID}/messages"\n';
  code += '        else:\n';
  code += '            api_url = f"https://{API_BASE_URL}/api/projects/{PROJECT_ID}/messages"\n';
  code += '        \n';
  code += '        payload = {\n';
  code += '            "userId": str(user_id),\n';
  code += '            "messageType": message_type,\n';
  code += '            "messageText": message_text,\n';
  code += '            "nodeId": node_id,\n';
  code += '            "messageData": message_data or {}\n';
  code += '        }\n';
  code += '        \n';
  code += '        logging.debug(f"💾 Отправка сообщения в API: {payload}")\n';
  code += '        \n';
  code += '        # Определяем, использовать ли SSL\n';
  code += '        use_ssl = not (api_url.startswith("http://") or "localhost" in api_url or "127.0.0.1" in api_url or "0.0.0.0" in api_url)\n';
  code += '        \n';
  code += '        if use_ssl:\n';
  code += '            # Для внешних соединений используем SSL-контекст\n';
  code += '            connector = aiohttp.TCPConnector(ssl=True)\n';
  code += '            session_params = {"connector": connector}\n';
  code += '        else:\n';
  code += '            # Для локальных соединений не используем SSL-контекст\n';
  code += '            session_params = {}\n';
  code += '        \n';
  code += '        async with aiohttp.ClientSession(**session_params) as session:\n';
  code += '            async with session.post(api_url, json=payload, timeout=aiohttp.ClientTimeout(total=5)) as response:\n';
  code += '                if response.status == 200:\n';
  code += '                    logging.info(f"✅ Сообщение сохранено: {message_type} от {user_id}")\n';
  code += '                    response_data = await response.json()\n';
  code += '                    return response_data.get("data")  # Возвращаем сохраненное сообщение с id\n';
  code += '                else:\n';
  code += '                    error_text = await response.text()\n';
  code += '                    logging.error(f"❌ Не удалось сохранить сообщение: {response.status} - {error_text}")\n';
  code += '                    logging.error(f"Отправленный payload: {payload}")\n';
  code += '                    return None\n';
  code += '    except Exception as e:\n';
  code += '        logging.error(f"Ошибка при сохранении сообщения: {e}")\n';
  code += '        return None\n\n';

  code += '# Middleware для сохранения входящих сообщений\n';
  code += 'async def message_logging_middleware(handler, event: types.Message, data: dict):\n';
  code += '    """Middleware для автоматического сохранения входящих сообщений от пользователей"""\n';
  code += '    try:\n';
  code += '        # Сохраняем входящее сообщение от пользователя\n';
  code += '        user_id = str(event.from_user.id)\n';
  code += '        message_text = event.text or event.caption or "[медиа]"\n';
  code += '        message_data = {"message_id": event.message_id}\n';
  code += '        \n';
  code += '        # Проверяем наличие фото\n';
  code += '        photo_file_id = None\n';
  code += '        if event.photo:\n';
  code += '            # Берем фото наибольшего размера (последнее в списке)\n';
  code += '            largest_photo = event.photo[-1]\n';
  code += '            photo_file_id = largest_photo.file_id\n';
  code += '            message_data["photo"] = {\n';
  code += '                "file_id": largest_photo.file_id,\n';
  code += '                "file_unique_id": largest_photo.file_unique_id,\n';
  code += '                "width": largest_photo.width,\n';
  code += '                "height": largest_photo.height,\n';
  code += '                "file_size": largest_photo.file_size if hasattr(largest_photo, "file_size") else None\n';
  code += '            }\n';
  code += '            if not message_text or message_text == "[медиа]":\n';
  code += '                message_text = "[Фото]"\n';
  code += '        \n';
  code += '        # Сохраняем сообщение в базу данных\n';
  code += '        saved_message = await save_message_to_api(\n';
  code += '            user_id=user_id,\n';
  code += '            message_type="user",\n';
  code += '            message_text=message_text,\n';
  code += '            message_data=message_data\n';
  code += '        )\n';
  code += '        \n';
  code += '        # Если есть фото и сообщение сохранено, регистрируем медиа\n';
  code += '        if photo_file_id and saved_message and "id" in saved_message:\n';
  code += '            try:\n';
  code += '                if API_BASE_URL.startswith("http://") or API_BASE_URL.startswith("https://"):\n';
  code += '                    media_api_url = f"{API_BASE_URL}/api/projects/{PROJECT_ID}/media/register-telegram-photo"\n';
  code += '                else:\n';
  code += '                    media_api_url = f"https://{API_BASE_URL}/api/projects/{PROJECT_ID}/media/register-telegram-photo"\n';
  code += '                \n';
  code += '                media_payload = {\n';
  code += '                    "messageId": saved_message["id"],\n';
  code += '                    "fileId": photo_file_id,\n';
  code += '                    "botToken": BOT_TOKEN,\n';
  code += '                    "mediaType": "photo"\n';
  code += '                }\n';
  code += '                \n';
  code += '                # Определяем, использовать ли SSL для медиа-запросов\n';
  code += '                use_ssl_media = not (media_api_url.startswith("http://") or "localhost" in media_api_url or "127.0.0.1" in media_api_url or "0.0.0.0" in media_api_url)\n';
  code += '                \n';
  code += '                if use_ssl_media:\n';
  code += '                    # Для внешних соединений используем SSL-контекст\n';
  code += '                    connector = aiohttp.TCPConnector(ssl=True)\n';
  code += '                    session_params = {"connector": connector}\n';
  code += '                else:\n';
  code += '                    # Для локальных соединений не используем SSL-контекст\n';
  code += '                    session_params = {}\n';
  code += '                \n';
  code += '                async with aiohttp.ClientSession(**session_params) as session:\n';
  code += '                    async with session.post(media_api_url, json=media_payload, timeout=aiohttp.ClientTimeout(total=10)) as response:\n';
  code += '                        if response.status == 200:\n';
  code += '                            message_id = saved_message.get("id")\n';
  code += '                            logging.info(f"✅ Медиа зарегистрировано для сообщения {message_id}")\n';
  code += '                        else:\n';
  code += '                            error_text = await response.text()\n';
  code += '                            logging.warning(f"⚠️ Не удалось зарегистрировать медиа: {response.status} - {error_text}")\n';
  code += '            except Exception as media_error:\n';
  code += '                logging.warning(f"Ошибка при регистрации медиа: {media_error}")\n';
  code += '    except Exception as e:\n';
  code += '        logging.error(f"Ошибка в middleware сохранения сообщений: {e}")\n';
  code += '    \n';
  code += '    # Продолжаем обработку сообщения\n';
  code += '    return await handler(event, data)\n\n';

  // Добавляем callback_query middleware только если в боте есть inline кнопки
  if (hasInlineButtons(nodes || [])) {
    code += '# Middleware для сохранения нажатий на кнопки\n';
    code += 'async def callback_query_logging_middleware(handler, event: types.CallbackQuery, data: dict):\n';
    code += '    """Middleware для автоматического сохранения нажатий на кнопки"""\n';
    code += '    try:\n';
    code += '        user_id = str(event.from_user.id)\n';
    code += '        callback_data = event.data or ""\n';
    code += '        \n';
    code += '        # Пытаемся найти текст кнопки из сообщения\n';
    code += '        button_text = None\n';
    code += '        if event.message and hasattr(event.message, "reply_markup"):\n';
    code += '            reply_markup = event.message.reply_markup\n';
    code += '            if hasattr(reply_markup, "inline_keyboard"):\n';
    code += '                for row in reply_markup.inline_keyboard:\n';
    code += '                    for btn in row:\n';
    code += '                        if hasattr(btn, "callback_data") and btn.callback_data == callback_data:\n';
    code += '                            button_text = btn.text\n';
    code += '                            break\n';
    code += '                    if button_text:\n';
    code += '                        break\n';
    code += '        \n';
    code += '        # Сохраняем информацию о нажатии кнопки\n';
    code += '        message_text_to_save = f"[Нажата кнопка: {button_text}]" if button_text else "[Нажата кнопка]"\n';
    code += '        await save_message_to_api(\n';
    code += '            user_id=user_id,\n';
    code += '            message_type="user",\n';
    code += '            message_text=message_text_to_save,\n';
    code += '            message_data={\n';
    code += '                "button_clicked": True,\n';
    code += '                "button_text": button_text,\n';
    code += '                "callback_data": callback_data\n';
    code += '            }\n';
    code += '        )\n';
    code += '    except Exception as e:\n';
    code += '        logging.error(f"Ошибка в middleware сохранения нажатий кнопок: {e}")\n';
    code += '    \n';
    code += '    # Продолжаем обработку callback query\n';
    code += '    return await handler(event, data)\n\n';
  }

  return code;
}
