import { Node, Connection } from '@shared/schema';

// Кеш для предотвращения повторных вызовов
let lastGenerationTime = 0;
let lastGenerationHash = '';

/**
 * Генерирует автоматические соединения для узлов с autoTransitionTo
 * @param nodes - Массив всех узлов
 * @param existingConnections - Существующие соединения
 * @returns Объединенный массив: ручные соединения + автогенерированные (переиспользованные или новые)
 */
export function generateAutoTransitionConnections(
  nodes: Node[],
  existingConnections: Connection[]
): Connection[] {
  // Создаем хеш для проверки изменений
  const currentHash = JSON.stringify(nodes.map(n => ({ id: n.id, type: n.type, inputTargetNodeId: n.data.inputTargetNodeId, autoTransitionTo: n.data.autoTransitionTo })));
  const now = Date.now();

  // Пропускаем вызов, если данные не изменились и прошло меньше 100мс
  if (currentHash === lastGenerationHash && now - lastGenerationTime < 100) {
    return existingConnections;
  }

  lastGenerationHash = currentHash;
  lastGenerationTime = now;

  console.log('🔍 Генерация автопереходов для', nodes.length, 'узлов');

  const manualConnections = existingConnections.filter(c => !c.isAutoGenerated);
  const existingAutoConnections = existingConnections.filter(c => c.isAutoGenerated);

  const autoConnections: Connection[] = [];

  for (const node of nodes) {
    // 1. Обрабатываем автопереходы (autoTransitionTo)
    if (node.data.autoTransitionTo) {
      console.log(`📍 Узел ${node.id} имеет автопереход к ${node.data.autoTransitionTo}`);

      const targetNode = nodes.find(n => n.id === node.data.autoTransitionTo);

      if (targetNode) {
        const autoConnectionId = `auto-${node.id}-${node.data.autoTransitionTo}`;

        const existingAuto = existingAutoConnections.find(c => c.id === autoConnectionId);

        if (existingAuto) {
          console.log(`♻️ Переиспользуем существующий автопереход ${autoConnectionId}`);
          autoConnections.push(existingAuto);
        } else {
          const hasManualConnection = manualConnections.some(
            c => c.source === node.id && c.target === node.data.autoTransitionTo
          );

          if (!hasManualConnection) {
            console.log(`✨ Создаем новый автопереход ${autoConnectionId}`);
            autoConnections.push({
              id: autoConnectionId,
              source: node.id,
              target: node.data.autoTransitionTo,
              isAutoGenerated: true,
              isInterSheet: false,
            });
          } else {
            console.log(`⚠️ Пропускаем автопереход ${autoConnectionId} - есть ручное соединение`);
          }
        }
      } else {
        console.log(`❌ Целевой узел ${node.data.autoTransitionTo} не найден`);
      }
    }

    // 2. Обрабатываем переходы после ввода (inputTargetNodeId)
    if (node.data.inputTargetNodeId) {
      console.log(`📍 Узел ${node.id} имеет inputTargetNodeId: ${node.data.inputTargetNodeId}`);
      const targetId = node.data.inputTargetNodeId;
      const targetNode = nodes.find(n => n.id === targetId);

      if (targetNode) {
        const autoConnectionId = `input-${node.id}-${targetId}`;
        const existingAuto = existingAutoConnections.find(c => c.id === autoConnectionId);

        if (existingAuto) {
          console.log(`♻️ Переиспользуем существующий автопереход после ввода ${autoConnectionId}`);
          autoConnections.push(existingAuto);
        } else {
          const hasManualConnection = manualConnections.some(
            c => c.source === node.id && c.target === targetId
          );

          if (!hasManualConnection) {
            console.log(`✨ Создаем новый автопереход после ввода ${autoConnectionId}`);
            autoConnections.push({
              id: autoConnectionId,
              source: node.id,
              target: targetId,
              isAutoGenerated: true,
              isInterSheet: false,
            });
          } else {
            console.log(`⚠️ Пропускаем автопереход после ввода ${autoConnectionId} - есть ручное соединение`);
          }
        }
      } else {
        console.log(`❌ Целевой узел ${targetId} для inputTargetNodeId не найден`);
      }
    }

    // 3. Обрабатываем переходы через кнопки (buttons[].target)
    if (node.data.buttons && Array.isArray(node.data.buttons)) {
      node.data.buttons.forEach((button: any) => {
        if (button.target) {
          const targetId = button.target;
          const targetNode = nodes.find(n => n.id === targetId);

          if (targetNode) {
            const autoConnectionId = `button-${node.id}-${button.id}-${targetId}`;
            const existingAuto = existingAutoConnections.find(c => c.id === autoConnectionId);

            if (existingAuto) {
              autoConnections.push(existingAuto);
            } else {
              const hasManualConnection = manualConnections.some(
                c => c.source === node.id && c.target === targetId
              );

              if (!hasManualConnection) {
                autoConnections.push({
                  id: autoConnectionId,
                  source: node.id,
                  target: targetId,
                  isAutoGenerated: true,
                  isInterSheet: false,
                });
              }
            }
          }
        }
      });
    }
  }

  console.log(`📊 Итого соединений: ${manualConnections.length} ручных + ${autoConnections.length} автогенерированных`);
  return [...manualConnections, ...autoConnections];
}

/**
 * Удаляет все автоматически сгенерированные соединения
 * @param connections - Массив соединений
 * @returns Только ручные соединения
 */
export function removeAutoGeneratedConnections(connections: Connection[]): Connection[] {
  return connections.filter(c => !c.isAutoGenerated);
}

/**
 * Проверяет, есть ли у узла автопереход и валиден ли он
 * @param node - Узел для проверки
 * @param allNodes - Все узлы для проверки существования целевого узла
 * @returns true, если автопереход валиден
 */
export function hasValidAutoTransition(node: Node, allNodes: Node[]): boolean {
  if (!node.data.autoTransitionTo) {
    return false;
  }

  const targetNode = allNodes.find(n => n.id === node.data.autoTransitionTo);
  return !!targetNode;
}