// Local type definitions for sheets-manager to avoid shared schema issues

export interface ButtonWithTarget {
  id: string;
  text: string;
  action: 'goto' | 'command' | 'url' | 'contact' | 'location' | 'selection' | 'default';
  target?: string;
  url?: string;
  requestContact?: boolean;
  requestLocation?: boolean;
  buttonType?: 'normal' | 'option' | 'complete';
  skipDataCollection?: boolean;
  hideAfterClick?: boolean;
  [key: string]: any;
}

export interface ConditionalMessageWithTarget {
  target?: string;
  buttons?: ButtonWithTarget[];
  [key: string]: any;
}

export interface CommandWithTarget {
  target?: string;
  [key: string]: any;
}

export interface OptionWithTarget {
  target?: string;
  [key: string]: any;
}

export interface NodeData {
  messageText?: string;
  description?: string;
  keyboardType?: 'reply' | 'inline' | 'none';
  buttons?: ButtonWithTarget[];
  oneTimeKeyboard?: boolean;
  resizeKeyboard?: boolean;
  markdown?: boolean;
  formatMode?: 'html' | 'markdown' | 'none';
  isPrivateOnly?: boolean;
  adminOnly?: boolean;
  requiresAuth?: boolean;
  showInMenu?: boolean;
  enableStatistics?: boolean;
  customParameters?: string[];
  options?: OptionWithTarget[];
  command?: string;
  synonyms?: string[];
  conditionalMessages?: ConditionalMessageWithTarget[];
  commands?: CommandWithTarget[];
  inputConfig?: {
    next_node_id?: string;
    [key: string]: any;
  };
  [key: string]: any;
}

export interface Node {
  id: string;
  type: string;
  position: { x: number; y: number };
  data: NodeData;
}

export interface Connection {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string;
  targetHandle?: string;
  sourceSheetId?: string;
  targetSheetId?: string;
  isInterSheet?: boolean;
  isAutoGenerated?: boolean;
}

export interface SheetViewState {
  pan: { x: number; y: number };
  zoom: number;
}

export interface CanvasSheet {
  id: string;
  name: string;
  nodes: Node[];
  connections: Connection[];
  viewState: SheetViewState;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface BotDataWithSheets {
  sheets: CanvasSheet[];
  activeSheetId?: string;
  version: number;
}

export interface BotData {
  nodes: Node[];
  connections: Connection[];
}