/**
 * @fileoverview Extract nodes and connections from project data.
 *
 * Supports both the legacy `{ nodes, connections }` shape and the newer
 * sheets-based format. Also synthesizes graph connections from node data
 * when the project does not store an explicit `connections` array.
 */

import { BotData, BotDataWithSheets, Node } from '@shared/schema';

type GraphConnection = {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string;
  targetHandle?: string;
  sourceSheetId?: string;
  targetSheetId?: string;
  isInterSheet?: boolean;
  isAutoGenerated?: boolean;
};

type LegacyBotData = BotData & {
  connections?: GraphConnection[];
};

type LegacySheet = BotDataWithSheets['sheets'][number] & {
  connections?: GraphConnection[];
};

function hasSheetsStructure(data: BotData | BotDataWithSheets): data is BotDataWithSheets {
  return 'sheets' in data && Array.isArray((data as BotDataWithSheets).sheets);
}

function getLegacyConnections(data: unknown): GraphConnection[] {
  if (!data || typeof data !== 'object') {
    return [];
  }

  const maybeConnections = (data as { connections?: GraphConnection[] }).connections;
  return Array.isArray(maybeConnections) ? maybeConnections : [];
}

function transformNodeData(nodes: Node[]): Node[] {
  if (!Array.isArray(nodes)) {
    return [];
  }

  return nodes
    .filter((node): node is Node => node !== null && node !== undefined)
    .map(node => {
      const hasImage = node.data?.imageUrl;
      const hasVideo = node.data?.videoUrl;
      const hasAudio = node.data?.audioUrl;
      const hasDocument = node.data?.documentUrl;

      if (
        (hasImage || hasVideo || hasAudio || hasDocument) &&
        (!node.data.attachedMedia || !Array.isArray(node.data.attachedMedia))
      ) {
        const mediaVariables: string[] = [];

        if (hasImage) mediaVariables.push(`image_url_${node.id}`);
        if (hasVideo) mediaVariables.push(`video_url_${node.id}`);
        if (hasAudio) mediaVariables.push(`audio_url_${node.id}`);
        if (hasDocument) mediaVariables.push(`document_url_${node.id}`);

        return {
          ...node,
          data: {
            ...node.data,
            attachedMedia: mediaVariables,
            ...(hasImage && { [`image_url_${node.id}`]: node.data.imageUrl }),
            ...(hasVideo && { [`video_url_${node.id}`]: node.data.videoUrl }),
            ...(hasAudio && { [`audio_url_${node.id}`]: node.data.audioUrl }),
            ...(hasDocument && { [`document_url_${node.id}`]: node.data.documentUrl }),
          },
        };
      }

      return node;
    });
}

function transformConnectionData(connections: GraphConnection[]): GraphConnection[] {
  if (!Array.isArray(connections)) {
    return [];
  }

  return connections.filter(
    (connection): connection is GraphConnection => connection !== null && connection !== undefined
  );
}

function buildConnectionKey(connection: Pick<GraphConnection, 'source' | 'target' | 'sourceHandle' | 'targetHandle'>): string {
  return [
    connection.source,
    connection.target,
    connection.sourceHandle || '',
    connection.targetHandle || '',
  ].join('::');
}

function mergeConnections(primary: GraphConnection[], fallback: GraphConnection[]): GraphConnection[] {
  const merged: GraphConnection[] = [];
  const seen = new Set<string>();

  for (const connection of [...primary, ...fallback]) {
    const key = buildConnectionKey(connection);
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    merged.push(connection);
  }

  return merged;
}

function synthesizeConnectionsFromNodes(nodes: Node[]): GraphConnection[] {
  const result: GraphConnection[] = [];
  const existingIds = new Set(nodes.map(node => node.id));
  const seen = new Set<string>();

  const pushConnection = (
    source: unknown,
    target: unknown,
    extra: Partial<GraphConnection> = {}
  ) => {
    if (typeof source !== 'string' || !source.trim()) return;
    if (typeof target !== 'string' || !target.trim()) return;
    if (!existingIds.has(source) || !existingIds.has(target)) return;

    const connection: GraphConnection = {
      id: extra.id || `synthetic_${source}_${target}_${result.length}`,
      source,
      target,
      sourceHandle: extra.sourceHandle,
      targetHandle: extra.targetHandle,
      sourceSheetId: extra.sourceSheetId,
      targetSheetId: extra.targetSheetId,
      isInterSheet: extra.isInterSheet,
      isAutoGenerated: extra.isAutoGenerated ?? true,
    };

    const key = buildConnectionKey(connection);
    if (seen.has(key)) return;
    seen.add(key);
    result.push(connection);
  };

  for (const node of nodes) {
    const data = node.data as Record<string, unknown> | undefined;
    if (!data) continue;

    pushConnection(node.id, data.autoTransitionTo, { sourceHandle: 'auto-transition' });
    pushConnection(node.id, data.inputTargetNodeId, { sourceHandle: 'input-target' });
    pushConnection(node.id, data.keyboardNodeId, { sourceHandle: 'keyboard-link' });
    pushConnection(data.sourceNodeId, node.id, { targetHandle: 'source-node' });

    const buttons = Array.isArray(data.buttons) ? data.buttons : [];
    buttons.forEach((button, index) => {
      if (!button || typeof button !== 'object') return;

      const typedButton = button as {
        action?: unknown;
        target?: unknown;
        id?: unknown;
      };

      if (typedButton.action === 'goto') {
        pushConnection(node.id, typedButton.target, {
          sourceHandle: typeof typedButton.id === 'string' && typedButton.id.trim()
            ? typedButton.id
            : `button_${index}`,
        });
      }
    });

    const branches = Array.isArray(data.branches) ? data.branches : [];
    branches.forEach((branch, index) => {
      if (!branch || typeof branch !== 'object') return;

      const typedBranch = branch as {
        target?: unknown;
        id?: unknown;
        operator?: unknown;
      };

      pushConnection(node.id, typedBranch.target, {
        sourceHandle: typeof typedBranch.id === 'string' && typedBranch.id.trim()
          ? typedBranch.id
          : `branch_${typeof typedBranch.operator === 'string' ? typedBranch.operator : index}`,
      });
    });
  }

  return result;
}

export function extractNodesAndConnections(botData: BotData | BotDataWithSheets) {
  if (!botData) {
    return { nodes: [], connections: [] };
  }

  if (hasSheetsStructure(botData)) {
    let allNodes: Node[] = [];
    let legacyConnections: GraphConnection[] = [];

    botData.sheets.forEach(sheet => {
      if (sheet.nodes && Array.isArray(sheet.nodes)) {
        const transformedNodes = transformNodeData(sheet.nodes);
        allNodes = allNodes.concat(transformedNodes);
      }

      const transformedConnections = transformConnectionData(
        getLegacyConnections(sheet as LegacySheet)
      );
      if (transformedConnections.length > 0) {
        legacyConnections = legacyConnections.concat(transformedConnections);
      }
    });

    const synthesizedConnections = synthesizeConnectionsFromNodes(allNodes);
    return {
      nodes: allNodes,
      connections: mergeConnections(legacyConnections, synthesizedConnections),
    };
  }

  const transformedNodes = transformNodeData(botData.nodes || []);
  const legacyConnections = transformConnectionData(
    getLegacyConnections(botData as LegacyBotData)
  );
  const synthesizedConnections = synthesizeConnectionsFromNodes(transformedNodes);

  return {
    nodes: transformedNodes,
    connections: mergeConnections(legacyConnections, synthesizedConnections),
  };
}
