/**
 * @fileoverview Извлечение узлов и соединений из данных проекта
 *
 * Модуль поддерживает и старую структуру `{ nodes, connections }`, и новую структуру с `sheets[]`.
 * Он также выполняет минимальную нормализацию legacy-данных узлов, не затрагивая семантику графа.
 *
 * @module bot-generator/core/extract-nodes-and-connections
 */

import { BotData, BotDataWithSheets, Node } from '@shared/schema';

// ============================================================================
// УТИЛИТЫ ДЛЯ РАБОТЫ С ДАННЫМИ БОТА
// ============================================================================

function hasSheetsStructure(data: BotData | BotDataWithSheets): data is BotDataWithSheets {
  return 'sheets' in data && Array.isArray((data as BotDataWithSheets).sheets);
}

/**
 * Преобразует данные узлов, добавляя медиа-URL в attachedMedia.
 */
function transformNodeData(nodes: Node[]): Node[] {
  if (!Array.isArray(nodes)) {
    return [];
  }
  return nodes
    .filter(node => node !== null && node !== undefined)
    .map(node => {
    const hasImage = node.data?.imageUrl;
    const hasVideo = node.data?.videoUrl;
    const hasAudio = node.data?.audioUrl;
    const hasDocument = node.data?.documentUrl;

    if ((hasImage || hasVideo || hasAudio || hasDocument) && (!node.data.attachedMedia || !Array.isArray(node.data.attachedMedia))) {
      const mediaVariables = [];

      if (hasImage) mediaVariables.push(`image_url_${node.id}`);
      if (hasVideo) mediaVariables.push(`video_url_${node.id}`);
      if (hasAudio) mediaVariables.push(`audio_url_${node.id}`);
      if (hasDocument) mediaVariables.push(`document_url_${node.id}`);

      return {
        ...node,
        data: {
          ...node.data,
          attachedMedia: mediaVariables,
          ...(hasImage && { [`image_url_${node.id}`]: node.data.imageUrl }),
          ...(hasVideo && { [`video_url_${node.id}`]: node.data.videoUrl }),
          ...(hasAudio && { [`audio_url_${node.id}`]: node.data.audioUrl }),
          ...(hasDocument && { [`document_url_${node.id}`]: node.data.documentUrl })
        }
      };
    }

    return node;
  });
}

/**
 * Собирает и фильтрует соединения из данных проекта.
 *
 * @param connections - Исходный массив соединений
 * @returns Нормализованный массив соединений
 */
function transformConnectionData(connections: GraphConnection[]): GraphConnection[] {
  if (!Array.isArray(connections)) {
    return [];
  }

  return connections.filter(connection => connection !== null && connection !== undefined);
}

/**
 * Извлекает и объединяет все узлы и связи из данных бота.
 */
export function extractNodesAndConnections(botData: BotData | BotDataWithSheets) {
  if (!botData) return { nodes: [], connections: [] };

  if (hasSheetsStructure(botData)) {
    let allNodes: Node[] = [];
    let allConnections: GraphConnection[] = [];

    botData.sheets.forEach((sheet) => {
      if (sheet.nodes && Array.isArray(sheet.nodes)) {
        const transformedNodes = transformNodeData(sheet.nodes);
        allNodes = allNodes.concat(transformedNodes);
      }

      if (sheet.connections && Array.isArray(sheet.connections)) {
        const transformedConnections = transformConnectionData(sheet.connections);
        allConnections = allConnections.concat(transformedConnections);
      }
    });

    return { nodes: allNodes, connections: allConnections };
  } else {
    const transformedNodes = transformNodeData(botData.nodes || []);
    const transformedConnections = transformConnectionData(botData.connections || []);
    return { nodes: transformedNodes, connections: transformedConnections };
  }
}
/**
 * Соединение графа проекта.
 */
type GraphConnection = {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string;
  targetHandle?: string;
  sourceSheetId?: string;
  targetSheetId?: string;
  isInterSheet?: boolean;
  isAutoGenerated?: boolean;
};
