/**
 * @fileoverview Extract nodes and connections from project data.
 *
 * Supports both the legacy `{ nodes, connections }` shape and the newer
 * sheets-based format. Also performs a small normalization for media fields.
 */

import { BotData, BotDataWithSheets, Node } from '@shared/schema';

type GraphConnection = {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string;
  targetHandle?: string;
  sourceSheetId?: string;
  targetSheetId?: string;
  isInterSheet?: boolean;
  isAutoGenerated?: boolean;
};

type LegacyBotData = BotData & {
  connections?: GraphConnection[];
};

type LegacySheet = BotDataWithSheets['sheets'][number] & {
  connections?: GraphConnection[];
};

function hasSheetsStructure(data: BotData | BotDataWithSheets): data is BotDataWithSheets {
  return 'sheets' in data && Array.isArray((data as BotDataWithSheets).sheets);
}

function getLegacyConnections(data: unknown): GraphConnection[] {
  if (!data || typeof data !== 'object') {
    return [];
  }

  const maybeConnections = (data as { connections?: GraphConnection[] }).connections;
  return Array.isArray(maybeConnections) ? maybeConnections : [];
}

function transformNodeData(nodes: Node[]): Node[] {
  if (!Array.isArray(nodes)) {
    return [];
  }

  return nodes
    .filter((node): node is Node => node !== null && node !== undefined)
    .map(node => {
      const hasImage = node.data?.imageUrl;
      const hasVideo = node.data?.videoUrl;
      const hasAudio = node.data?.audioUrl;
      const hasDocument = node.data?.documentUrl;

      if (
        (hasImage || hasVideo || hasAudio || hasDocument) &&
        (!node.data.attachedMedia || !Array.isArray(node.data.attachedMedia))
      ) {
        const mediaVariables: string[] = [];

        if (hasImage) mediaVariables.push(`image_url_${node.id}`);
        if (hasVideo) mediaVariables.push(`video_url_${node.id}`);
        if (hasAudio) mediaVariables.push(`audio_url_${node.id}`);
        if (hasDocument) mediaVariables.push(`document_url_${node.id}`);

        return {
          ...node,
          data: {
            ...node.data,
            attachedMedia: mediaVariables,
            ...(hasImage && { [`image_url_${node.id}`]: node.data.imageUrl }),
            ...(hasVideo && { [`video_url_${node.id}`]: node.data.videoUrl }),
            ...(hasAudio && { [`audio_url_${node.id}`]: node.data.audioUrl }),
            ...(hasDocument && { [`document_url_${node.id}`]: node.data.documentUrl }),
          },
        };
      }

      return node;
    });
}

function transformConnectionData(connections: GraphConnection[]): GraphConnection[] {
  if (!Array.isArray(connections)) {
    return [];
  }

  return connections.filter(
    (connection): connection is GraphConnection => connection !== null && connection !== undefined
  );
}

export function extractNodesAndConnections(botData: BotData | BotDataWithSheets) {
  if (!botData) {
    return { nodes: [], connections: [] };
  }

  if (hasSheetsStructure(botData)) {
    let allNodes: Node[] = [];
    let allConnections: GraphConnection[] = [];

    botData.sheets.forEach(sheet => {
      if (sheet.nodes && Array.isArray(sheet.nodes)) {
        const transformedNodes = transformNodeData(sheet.nodes);
        allNodes = allNodes.concat(transformedNodes);
      }

      const transformedConnections = transformConnectionData(
        getLegacyConnections(sheet as LegacySheet)
      );
      if (transformedConnections.length > 0) {
        allConnections = allConnections.concat(transformedConnections);
      }
    });

    return { nodes: allNodes, connections: allConnections };
  }

  const transformedNodes = transformNodeData(botData.nodes || []);
  const transformedConnections = transformConnectionData(
    getLegacyConnections(botData as LegacyBotData)
  );
  return { nodes: transformedNodes, connections: transformedConnections };
}
