/**
 * Утилита для автоматического добавления комментариев о генерации кода
 */

let commentsStateGetter: () => boolean = () => true;

/**
 * Инициализирует источник состояния комментариев из GenerationState.
 */
export function initCommentsState(getter: () => boolean): void {
  commentsStateGetter = getter;
}

/**
 * Возвращает текущее состояние генерации комментариев
 */
export function areCommentsEnabled(): boolean {
  return commentsStateGetter();
}

/**
 * Добавляет комментарий о том, что код сгенерирован в определённом файле
 */
export function addGeneratedComment(
  code: string,
  generatorFile: string,
  additionalInfo?: string
): string {
  if (!areCommentsEnabled()) return code;
  const baseComment = `# Код сгенерирован в ${generatorFile}`;
  const fullComment = additionalInfo ? `${baseComment}: ${additionalInfo}` : baseComment;
  return `${fullComment}\n${code}`;
}

/**
 * Создаёт комментарий для блока проверок безопасности
 */
export function getSecurityCheckComment(checkType: 'private_chat' | 'admin' | 'auth'): string {
  if (!areCommentsEnabled()) return '';
  const comments = {
    private_chat: 'Проверка приватного чата (сгенерировано в generateCommandHandler.ts)',
    admin: 'Проверка прав администратора (сгенерировано в generateCommandHandler.ts)',
    auth: 'Проверка авторизации (сгенерировано в generateCommandHandler.ts)'
  };
  return comments[checkType];
}

/**
 * Создаёт комментарий для блока сохранения пользовательских данных
 */
export function getDataSavingComment(dataType: 'user_data' | 'statistics' | 'local_storage'): string {
  if (!areCommentsEnabled()) return '';
  const comments = {
    user_data: 'Сохранение пользователя и статистики (сгенерировано в generateCommandHandler.ts)',
    statistics: 'Обновление статистики команд (сгенерировано в generateCommandHandler.ts)',
    local_storage: 'Сохранение в локальное хранилище (сгенерировано в generateCommandHandler.ts)'
  };
  return comments[dataType];
}

/**
 * Создаёт комментарий для блока обработки сообщений
 */
export function getMessageProcessingComment(messageType: 'conditional' | 'fallback' | 'keyboard'): string {
  if (!areCommentsEnabled()) return '';
  const comments = {
    conditional: 'Обработка условных сообщений (сгенерировано в generateCommandHandler.ts)',
    fallback: 'Обработка запасного сообщения (сгенерировано в generateCommandHandler.ts)',
    keyboard: 'Генерация клавиатуры (сгенерировано в generateCommandHandler.ts)'
  };
  return comments[messageType];
}

/**
 * Автоматически добавляет комментарий о генерации к любому блоку кода
 */
export function autoGenerated(
  code: string,
  generatorFile: string,
  blockDescription?: string
): string {
  if (!areCommentsEnabled()) return code;
  const baseComment = `# Код сгенерирован в ${generatorFile}`;
  const fullComment = blockDescription ? `${baseComment}: ${blockDescription}` : baseComment;
  return `${fullComment}\n${code}`;
}

/**
 * Создаёт обёртку для кода с комментариями о генерации
 */
export function wrapWithGeneratedComments(
  codeLines: string[],
  generatorFile: string,
  blockDescription?: string
): string[] {
  if (!areCommentsEnabled()) return codeLines;
  const wrappedLines: string[] = [];
  if (codeLines.some(line => line.trim() && !line.trim().startsWith('#'))) {
    wrappedLines.push(`# Код сгенерирован в ${generatorFile}${blockDescription ? `: ${blockDescription}` : ''}`);
  }
  wrappedLines.push(...codeLines);
  return wrappedLines;
}

/**
 * Создаёт блок кода с автоматическими комментариями о генерации
 */
export function createGeneratedBlock(
  code: string,
  generatorFile: string,
  blockDescription?: string
): string {
  if (!areCommentsEnabled()) return code;
  const lines = code.split('\n').filter(line => line.trim());
  if (lines.length === 0) return '';
  if (lines[0].includes('Код сгенерирован в')) return code;
  return wrapWithGeneratedComments([code], generatorFile, blockDescription).join('\n');
}

/**
 * Обрабатывает массив строк кода и автоматически добавляет комментарии к непустым блокам
 */
export function processCodeWithAutoComments(
  codeLines: string[],
  generatorFile: string
): string[] {
  if (!areCommentsEnabled()) return [...codeLines];

  const result: string[] = [];
  let currentBlock: string[] = [];

  const flushBlock = () => {
    if (currentBlock.length > 0) {
      const hasRealCode = currentBlock.some(line =>
        line.trim() &&
        !line.trim().startsWith('#') &&
        !line.trim().startsWith('"""') &&
        !line.trim().startsWith("'''")
      );

      if (hasRealCode) {
        const firstNonEmptyLine = currentBlock.find(line => line.trim());
        if (!firstNonEmptyLine?.includes('Код сгенерирован в')) {
          const indent = firstNonEmptyLine ? firstNonEmptyLine.match(/^(\s*)/)?.[1] || '' : '';
          result.push(`${indent}# Код сгенерирован в ${generatorFile}`);
        }
      }

      result.push(...currentBlock);
      currentBlock = [];
    }
  };

  for (let i = 0; i < codeLines.length; i++) {
    const line = codeLines[i];
    if (!line.trim()) { currentBlock.push(line); continue; }
    if (line.includes('Код сгенерирован в')) { currentBlock.push(line); continue; }
    if (line.trim().startsWith('@') ||
        line.trim().startsWith('async def') ||
        line.trim().startsWith('def ') ||
        line.trim().startsWith('if ') && currentBlock.length > 0) {
      flushBlock();
    }
    currentBlock.push(line);
  }

  flushBlock();
  return result;
}
