/**
 * @fileoverview Экспорт ядра генератора ботов
 * Агрегирует конфигурацию и логирование
 */

export { globalLoggingEnabled, setGlobalLoggingEnabled, getGlobalLoggingEnabled } from './config';
export { isLoggingEnabled, logFlowAnalysis } from './logging';

// Утилиты узлов
export { addAutoTransitionNodes } from './add-auto-transition-nodes';
export { addInputTargetNodes } from './add-input-target-nodes';
export { collectInputTargetNodes } from './collect-input-target-nodes';
export { collectMediaVariables } from './collect-media-variables';
export { extractNodeData } from './extract-node-data';
export type { ExtractNodeDataResult } from './extract-node-data';
export { extractNodesAndConnections } from './extract-nodes-and-connections';
export { toEnhancedNode, toEnhancedNodes } from './to-enhanced-node';
export { collectAllCommandCallbacksFromNodes, findCommandNode } from './command-utils';
export { initCommentsState, areCommentsEnabled, addGeneratedComment, autoGenerated, processCodeWithAutoComments } from './generated-comment';
