/**
 * @fileoverview Тесты качества middleware в сгенерированном коде
 *
 * Проверяет:
 * - отсутствие глобального monkey-patching (types.Message.answer = ...)
 * - наличие BaseMiddleware класса
 * - наличие guard db_pool в save_message_to_api
 * - наличие callback_query_logging_middleware при наличии inline кнопок
 * - отсутствие более 3 пустых строк подряд
 * - наличие _wrap_bot_send_message / _wrap_bot_send_photo
 *
 * @module bot-generator/core/middleware-quality.test
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { generatePythonCode } from '../../bot-generator';
import type { BotData } from '@shared/schema';

// ---------------------------------------------------------------------------
// Фикстуры
// ---------------------------------------------------------------------------

function makeBotWithInlineButtons(): BotData {
  return {
    nodes: [
      {
        id: 'start_1',
        type: 'start',
        position: { x: 0, y: 0 },
        data: {
          command: '/start',
          messageText: 'Привет!',
          buttons: [
            {
              id: 'btn_1',
              text: 'Перейти',
              action: 'goto',
              target: 'msg_1',
              hideAfterClick: false,
              skipDataCollection: false,
            },
          ],
          keyboardType: 'inline',
          adminOnly: false,
          requiresAuth: false,
          synonyms: [],
          showInMenu: true,
          description: 'Запустить бота',
          markdown: false,
          enableConditionalMessages: false,
          conditionalMessages: [],
        } as unknown as BotData['nodes'][number]['data'],
      },
      {
        id: 'msg_1',
        type: 'message',
        position: { x: 0, y: 300 },
        data: {
          messageText: 'Сообщение',
          buttons: [],
          keyboardType: 'inline',
          adminOnly: false,
          requiresAuth: false,
          synonyms: [],
          markdown: false,
          enableConditionalMessages: false,
          conditionalMessages: [],
          enableAutoTransition: false,
        } as unknown as BotData['nodes'][number]['data'],
      },
    ],
    connections: [
      { id: 'c1', source: 'start_1', target: 'msg_1', isInterSheet: false, isAutoGenerated: false },
    ],
  };
}

function makeSimpleBot(): BotData {
  return {
    nodes: [
      {
        id: 'start_1',
        type: 'start',
        position: { x: 0, y: 0 },
        data: {
          command: '/start',
          messageText: 'Привет!',
          buttons: [],
          keyboardType: 'none',
          adminOnly: false,
          requiresAuth: false,
          synonyms: [],
          showInMenu: true,
          description: 'Запустить бота',
          markdown: false,
          enableConditionalMessages: false,
          conditionalMessages: [],
        } as unknown as BotData['nodes'][number]['data'],
      },
    ],
    connections: [],
  };
}

// ---------------------------------------------------------------------------
// Monkey-patching — должен отсутствовать
// ---------------------------------------------------------------------------

describe('middleware-quality — нет глобального monkey-patching', () => {
  it('types.Message.answer не переопределяется глобально', () => {
    const code = generatePythonCode(makeBotWithInlineButtons(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      !code.includes('types.Message.answer = answer_with_logging'),
      'Глобальный monkey-patch types.Message.answer не должен присутствовать'
    );
  });

  it('bot.send_message не переопределяется глобально на уровне модуля', () => {
    const code = generatePythonCode(makeBotWithInlineButtons(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    // Допустимо только внутри функции _wrap_bot_send_message
    const globalPatch = /^bot\.send_message\s*=/m.test(code);
    assert.ok(!globalPatch, 'bot.send_message не должен переопределяться на уровне модуля');
  });

  it('bot.send_photo не переопределяется глобально на уровне модуля', () => {
    const code = generatePythonCode(makeBotWithInlineButtons(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    const globalPatch = /^bot\.send_photo\s*=/m.test(code);
    assert.ok(!globalPatch, 'bot.send_photo не должен переопределяться на уровне модуля');
  });
});

// ---------------------------------------------------------------------------
// BaseMiddleware — должен присутствовать
// ---------------------------------------------------------------------------

describe('middleware-quality — BaseMiddleware используется', () => {
  it('импортируется BaseMiddleware из aiogram', () => {
    const code = generatePythonCode(makeBotWithInlineButtons(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      code.includes('BaseMiddleware'),
      'BaseMiddleware должен быть импортирован из aiogram'
    );
  });

  it('BotOutgoingLoggingMiddleware определён как класс', () => {
    const code = generatePythonCode(makeBotWithInlineButtons(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      code.includes('class BotOutgoingLoggingMiddleware'),
      'BotOutgoingLoggingMiddleware должен быть определён как класс'
    );
  });
});

// ---------------------------------------------------------------------------
// db_pool guard в save_message_to_api
// ---------------------------------------------------------------------------

describe('middleware-quality — db_pool guard в save_message_to_api', () => {
  it('save_message_to_api проверяет db_pool перед использованием', () => {
    const code = generatePythonCode(makeSimpleBot(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    // Должна быть проверка if not db_pool: return None
    assert.ok(
      code.includes('if not db_pool:'),
      'save_message_to_api должна содержать guard "if not db_pool:"'
    );
  });
});

// ---------------------------------------------------------------------------
// callback_query_logging_middleware при наличии inline кнопок
// ---------------------------------------------------------------------------

describe('middleware-quality — callback_query_logging_middleware', () => {
  it('генерируется при наличии inline кнопок', () => {
    const code = generatePythonCode(makeBotWithInlineButtons(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      code.includes('callback_query_logging_middleware'),
      'callback_query_logging_middleware должен генерироваться при наличии inline кнопок'
    );
  });

  it('НЕ генерируется без inline кнопок', () => {
    const code = generatePythonCode(makeSimpleBot(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      !code.includes('callback_query_logging_middleware'),
      'callback_query_logging_middleware не должен генерироваться без inline кнопок'
    );
  });
});

// ---------------------------------------------------------------------------
// _wrap_bot_* функции
// ---------------------------------------------------------------------------

describe('middleware-quality — _wrap_bot_* функции', () => {
  it('_wrap_bot_send_message определена', () => {
    const code = generatePythonCode(makeSimpleBot(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      code.includes('def _wrap_bot_send_message('),
      '_wrap_bot_send_message должна быть определена'
    );
  });

  it('_wrap_bot_send_photo определена', () => {
    const code = generatePythonCode(makeSimpleBot(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      code.includes('def _wrap_bot_send_photo('),
      '_wrap_bot_send_photo должна быть определена'
    );
  });

  it('_wrap_bot_send_message вызывается в main()', () => {
    const code = generatePythonCode(makeSimpleBot(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      code.includes('_wrap_bot_send_message(bot)'),
      '_wrap_bot_send_message(bot) должна вызываться в main()'
    );
  });

  it('_wrap_bot_send_photo вызывается в main()', () => {
    const code = generatePythonCode(makeSimpleBot(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    assert.ok(
      code.includes('_wrap_bot_send_photo(bot)'),
      '_wrap_bot_send_photo(bot) должна вызываться в main()'
    );
  });
});

// ---------------------------------------------------------------------------
// Пустые строки — не более 3 подряд
// ---------------------------------------------------------------------------

describe('middleware-quality — нет избыточных пустых строк', () => {
  it('не более 3 пустых строк подряд в сгенерированном коде', () => {
    const code = generatePythonCode(makeBotWithInlineButtons(), {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });
    const hasExcessiveBlankLines = /\n{4,}/.test(code);
    assert.ok(
      !hasExcessiveBlankLines,
      'В коде не должно быть более 3 пустых строк подряд'
    );
  });

  it('не более 3 пустых строк подряд без БД', () => {
    const code = generatePythonCode(makeSimpleBot(), {
      botName: 'TestBot',
      userDatabaseEnabled: false,
    });
    const hasExcessiveBlankLines = /\n{4,}/.test(code);
    assert.ok(!hasExcessiveBlankLines);
  });
});
