/**
 * @fileoverview Нормализация отдельной keyboard-ноды перед генерацией
 *
 * Модуль переводит новую canvas-модель клавиатуры в совместимую с генератором форму:
 * - keyboard-нода остаётся в графе только как безопасный target;
 * - данные клавиатуры переносятся в ближайший message-контекст;
 * - старые встроенные клавиатуры продолжают работать без изменений.
 *
 * @module bot-generator/core/normalize-keyboard-bindings
 */

import type { Node } from '@shared/schema';
import { NODE_TYPES } from '../types';
import { generatorLogger } from './generator-logger';

/**
 * Соединение графа проекта.
 */
type GraphConnection = {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string;
  targetHandle?: string;
  sourceSheetId?: string;
  targetSheetId?: string;
  isInterSheet?: boolean;
  isAutoGenerated?: boolean;
};

/** Список типов узлов, которые могут владеть клавиатурой */
const KEYBOARD_HOST_TYPES = new Set<string>([
  NODE_TYPES.MESSAGE,
  NODE_TYPES.START,
  NODE_TYPES.COMMAND,
]);

/** Значения клавиатуры по умолчанию */
const KEYBOARD_FALLBACK_DATA = {
  buttons: [] as unknown[],
  keyboardType: 'none',
  keyboardLayout: undefined as unknown,
  oneTimeKeyboard: false,
  resizeKeyboard: true,
};

/**
 * Читает ID связанной keyboard-ноды из данных узла.
 *
 * @param data - Данные узла
 * @returns ID keyboard-ноды или `null`
 */
function readKeyboardNodeId(data: unknown): string | null {
  if (!data || typeof data !== 'object') return null;
  const keyboardNodeId = (data as { keyboardNodeId?: unknown }).keyboardNodeId;
  return typeof keyboardNodeId === 'string' && keyboardNodeId.trim() ? keyboardNodeId : null;
}

/**
 * Возвращает `true`, если тип узла может быть владельцем клавиатуры.
 *
 * @param nodeType - Тип узла
 * @returns `true`, если узел подходит для привязки клавиатуры
 */
function isKeyboardHostType(nodeType: string): boolean {
  return KEYBOARD_HOST_TYPES.has(nodeType);
}

/**
 * Создаёт карту входящих соединений по целевому узлу.
 *
 * @param connections - Соединения графа
 * @returns Карта `targetId -> sourceId[]`
 */
function buildIncomingMap(connections: GraphConnection[]): Map<string, string[]> {
  const incoming = new Map<string, string[]>();

  for (const connection of connections || []) {
    if (!connection || !connection.target || !connection.source) continue;
    const list = incoming.get(connection.target) || [];
    list.push(connection.source);
    incoming.set(connection.target, list);
  }

  return incoming;
}

/**
 * Глубоко не копирует, а только создаёт безопасную рабочую копию узла.
 *
 * @param node - Исходный узел
 * @returns Копия узла, пригодная для нормализации
 */
function cloneNode(node: Node): Node {
  return {
    ...node,
    data: { ...(node.data as Record<string, unknown>) },
  } as Node;
}

/**
 * Проверяет, содержит ли раскладка keyboard реальные настройки.
 *
 * Пустой объект от формы считаем отсутствием раскладки, чтобы не затирать
 * legacy-значения у message.
 *
 * @param layout - Раскладка keyboard
 * @returns `true`, если раскладка осмысленная
 */
function hasMeaningfulKeyboardLayout(layout: unknown): boolean {
  if (!layout || typeof layout !== 'object') return false;
  const candidate = layout as {
    rows?: unknown;
    autoLayout?: unknown;
    columns?: unknown;
  };

  return (
    (Array.isArray(candidate.rows) && candidate.rows.length > 0) ||
    candidate.autoLayout === true ||
    typeof candidate.columns === 'number'
  );
}

/**
 * Ищет все message-узлы, которые явно ссылаются на keyboard-ноду через `keyboardNodeId`.
 *
 * @param nodes - Все узлы графа
 * @param keyboardNodeId - ID keyboard-ноды
 * @returns Список ID владельцев
 */
function findExplicitKeyboardHostIds(nodes: Node[], keyboardNodeId: string): string[] {
  return nodes
    .filter(node => isKeyboardHostType(node.type) && readKeyboardNodeId(node.data) === keyboardNodeId)
    .map(node => node.id);
}

/**
 * Ищет ближайший message-контекст, поднимаясь по графу назад.
 *
 * @param keyboardNodeId - ID keyboard-ноды
 * @param nodeMap - Карта узлов по ID
 * @param incomingMap - Карта входящих соединений
 * @returns ID узла-владельца или `null`
 */
function findKeyboardHostByGraph(
  keyboardNodeId: string,
  nodeMap: Map<string, Node>,
  incomingMap: Map<string, string[]>
): string | null {
  const queue: string[] = [...(incomingMap.get(keyboardNodeId) || [])];
  const visited = new Set<string>([keyboardNodeId]);

  while (queue.length > 0) {
    const currentId = queue.shift() as string;
    if (visited.has(currentId)) continue;
    visited.add(currentId);

    const currentNode = nodeMap.get(currentId);
    if (!currentNode) continue;

    if (isKeyboardHostType(currentNode.type)) {
      return currentNode.id;
    }

    const incomingSources = incomingMap.get(currentId) || [];
    for (const sourceId of incomingSources) {
      if (!visited.has(sourceId)) {
        queue.push(sourceId);
      }
    }
  }

  return null;
}

/**
 * Подбирает кнопки для message-like узла с учётом legacy и новой модели.
 *
 * @param hostData - Данные узла-хозяина
 * @param keyboardData - Данные keyboard-ноды
 * @returns Обновлённые данные клавиатуры
 */
function buildMergedKeyboardData(
  hostData: Record<string, unknown>,
  keyboardData: Record<string, unknown>
): Record<string, unknown> {
  const hostButtons = Array.isArray(hostData.buttons) ? hostData.buttons : [];
  const keyboardButtons = Array.isArray(keyboardData.buttons) ? keyboardData.buttons : [];
  const hostLayout = hostData.keyboardLayout;
  const keyboardLayout = keyboardData.keyboardLayout;
  const hostKeyboardType = typeof hostData.keyboardType === 'string' ? hostData.keyboardType : 'none';
  const keyboardKeyboardType = typeof keyboardData.keyboardType === 'string' ? keyboardData.keyboardType : 'none';
  const resolvedButtons = keyboardButtons.length > 0 ? keyboardButtons : hostButtons;
  const resolvedKeyboardType = keyboardKeyboardType !== 'none' ? keyboardKeyboardType : hostKeyboardType;
  const resolvedKeyboardLayout = hasMeaningfulKeyboardLayout(keyboardLayout) ? keyboardLayout : hostLayout;
  const resolvedAllowMultipleSelection =
    typeof keyboardData.allowMultipleSelection === 'boolean'
      ? keyboardData.allowMultipleSelection
      : (typeof hostData.allowMultipleSelection === 'boolean' ? hostData.allowMultipleSelection : false);
  const resolvedMultiSelectVariable =
    typeof keyboardData.multiSelectVariable === 'string' && keyboardData.multiSelectVariable.trim()
      ? keyboardData.multiSelectVariable
      : (typeof hostData.multiSelectVariable === 'string' ? hostData.multiSelectVariable : undefined);
  const resolvedContinueButtonTarget =
    typeof keyboardData.continueButtonTarget === 'string' && keyboardData.continueButtonTarget.trim()
      ? keyboardData.continueButtonTarget
      : (typeof hostData.continueButtonTarget === 'string' ? hostData.continueButtonTarget : undefined);

  return {
    ...hostData,
    buttons: resolvedButtons,
    keyboardType: resolvedKeyboardType,
    keyboardLayout: resolvedKeyboardLayout,
    allowMultipleSelection: resolvedAllowMultipleSelection,
    multiSelectVariable: resolvedMultiSelectVariable,
    continueButtonTarget: resolvedContinueButtonTarget,
    oneTimeKeyboard: typeof keyboardData.oneTimeKeyboard === 'boolean'
      ? keyboardData.oneTimeKeyboard
      : (typeof hostData.oneTimeKeyboard === 'boolean' ? hostData.oneTimeKeyboard : false),
    resizeKeyboard: typeof keyboardData.resizeKeyboard === 'boolean'
      ? keyboardData.resizeKeyboard
      : (typeof hostData.resizeKeyboard === 'boolean' ? hostData.resizeKeyboard : true),
  };
}

/**
 * Очищает данные keyboard-ноды, чтобы она не выглядела как обычный message-like узел.
 *
 * @param node - keyboard-нода
 */
function clearKeyboardNodeData(node: Node): void {
  node.data = {
    buttons: KEYBOARD_FALLBACK_DATA.buttons,
    keyboardType: KEYBOARD_FALLBACK_DATA.keyboardType,
    keyboardLayout: KEYBOARD_FALLBACK_DATA.keyboardLayout,
    oneTimeKeyboard: KEYBOARD_FALLBACK_DATA.oneTimeKeyboard,
    resizeKeyboard: KEYBOARD_FALLBACK_DATA.resizeKeyboard,
  } as Node['data'];
}

/**
 * Нормализует новую модель keyboard-ноды к legacy-формату генератора.
 *
 * @param nodes - Список узлов графа
 * @param connections - Список соединений графа
 * @returns Копия узлов, готовая к генерации
 */
export function normalizeKeyboardBindings(nodes: Node[], connections: GraphConnection[]): Node[] {
  if (!Array.isArray(nodes) || nodes.length === 0) {
    return [];
  }

  const normalizedNodes = nodes
    .filter(node => node !== null && node !== undefined)
    .map(cloneNode);

  const nodeMap = new Map<string, Node>(normalizedNodes.map(node => [node.id, node]));
  const incomingMap = buildIncomingMap(connections || []);
  const processedKeyboardNodes = new Set<string>();

  for (const keyboardNode of normalizedNodes.filter(node => node.type === NODE_TYPES.KEYBOARD)) {
    const keyboardNodeId = keyboardNode.id;
    const explicitHostIds = findExplicitKeyboardHostIds(normalizedNodes, keyboardNodeId);
    const hostIds = explicitHostIds.length > 0
      ? explicitHostIds
      : (() => {
          const hostId = findKeyboardHostByGraph(keyboardNodeId, nodeMap, incomingMap);
          return hostId ? [hostId] : [];
        })();

    if (hostIds.length === 0) {
      generatorLogger.warn(`Не удалось привязать keyboard-ноду ${keyboardNodeId} к message, она будет проигнорирована`);
      clearKeyboardNodeData(keyboardNode);
      continue;
    }

    const keyboardData = keyboardNode.data as Record<string, unknown>;
    for (const hostId of hostIds) {
      const hostNode = nodeMap.get(hostId);
      if (!hostNode || !isKeyboardHostType(hostNode.type)) {
        continue;
      }
      const hostData = hostNode.data as Record<string, unknown>;
      hostNode.data = buildMergedKeyboardData(hostData, keyboardData) as Node['data'];
      delete (hostNode.data as Record<string, unknown>).keyboardNodeId;
    }

    clearKeyboardNodeData(keyboardNode);
    processedKeyboardNodes.add(keyboardNodeId);
  }

  if (processedKeyboardNodes.size > 0) {
    generatorLogger.debug(`Нормализованы keyboard-ноды: ${Array.from(processedKeyboardNodes).join(', ')}`);
  }

  return normalizedNodes;
}
