/**
 * @fileoverview Тест на раздутость генерируемого кода
 *
 * Проверяет, что медиа-функции НЕ генерируются для простых ботов
 * без медиа-узлов, даже если userDatabaseEnabled=true.
 *
 * @module templates/bloat-detection.test
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { generatePythonCode } from '../bot-generator';
import type { BotData } from '@shared/schema';

/** Минимальный BotData: start + message, без медиа, без переменных */
function makeMinimalBotData(): BotData {
  return {
    nodes: [
      {
        id: 'start_1',
        type: 'start',
        position: { x: 100, y: 100 },
        data: {
          command: '/start',
          messageText: 'Привет!',
          buttons: [],
          keyboardType: 'inline',
          isPrivateOnly: false,
          adminOnly: false,
          requiresAuth: false,
          synonyms: [],
          showInMenu: true,
          description: 'Запустить бота',
          markdown: false,
          enableConditionalMessages: false,
          conditionalMessages: [],
        } as unknown as BotData['nodes'][number]['data'],
      },
      {
        id: 'msg_1',
        type: 'message',
        position: { x: 100, y: 300 },
        data: {
          messageText: 'Простое сообщение',
          buttons: [],
          keyboardType: 'inline',
          isPrivateOnly: false,
          adminOnly: false,
          requiresAuth: false,
          synonyms: [],
          markdown: false,
          enableConditionalMessages: false,
          conditionalMessages: [],
          enableAutoTransition: false,
        } as unknown as BotData['nodes'][number]['data'],
      },
    ],
    connections: [
      {
        id: 'conn_1',
        source: 'start_1',
        target: 'msg_1',
        isInterSheet: false,
        isAutoGenerated: false,
      },
    ],
  };
}

/** Медиа-функции, которые НЕ должны присутствовать в простом боте */
const MEDIA_FUNCTIONS = [
  'save_media_to_db',
  'link_media_to_message',
  'send_photo_with_caption',
  'register_telegram_photo',
  'get_upload_file_path',
];

/** Обязательные компоненты, которые ДОЛЖНЫ присутствовать */
const REQUIRED_COMPONENTS = [
  'async def main()',
  'Dispatcher()',
];

/**
 * Считает количество вхождений подстроки в строке
 */
function countOccurrences(haystack: string, needle: string): number {
  let count = 0;
  let pos = 0;
  while ((pos = haystack.indexOf(needle, pos)) !== -1) {
    count++;
    pos += needle.length;
  }
  return count;
}

describe('bloat-detection — медиа-функции не генерируются без медиа-узлов', () => {
  it('не должен содержать медиа-функции при userDatabaseEnabled=true без медиа-узлов', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });

    for (const fn of MEDIA_FUNCTIONS) {
      assert.ok(
        !code.includes(`def ${fn}`),
        `Код не должен содержать функцию "${fn}" для бота без медиа-узлов`
      );
    }
  });

  it('не должен содержать медиа-функции при userDatabaseEnabled=false без медиа-узлов', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: false,
    });

    for (const fn of MEDIA_FUNCTIONS) {
      assert.ok(
        !code.includes(`def ${fn}`),
        `Код не должен содержать функцию "${fn}" при userDatabaseEnabled=false`
      );
    }
  });

  it('должен содержать обязательные компоненты при userDatabaseEnabled=true', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });

    for (const component of REQUIRED_COMPONENTS) {
      assert.ok(
        code.includes(component),
        `Код должен содержать "${component}"`
      );
    }
  });

  it('должен содержать обязательные компоненты при userDatabaseEnabled=false', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: false,
    });

    for (const component of REQUIRED_COMPONENTS) {
      assert.ok(
        code.includes(component),
        `Код должен содержать "${component}"`
      );
    }
  });
});

describe('bloat-detection — дублирование функций', () => {
  it('save_message_to_api должна быть определена ровно один раз при userDatabaseEnabled=true', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });

    const count = countOccurrences(code, 'async def save_message_to_api(');
    assert.strictEqual(
      count,
      1,
      `"async def save_message_to_api" должна встречаться ровно 1 раз, найдено: ${count}`
    );
  });

  it('save_message_to_api должна быть определена ровно один раз при userDatabaseEnabled=false', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: false,
    });

    const count = countOccurrences(code, 'async def save_message_to_api(');
    assert.strictEqual(
      count,
      1,
      `"async def save_message_to_api" должна встречаться ровно 1 раз, найдено: ${count}`
    );
  });

  it('save_message_to_api должна быть определена ровно один раз при userDatabaseEnabled=true и projectId', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: true,
      projectId: 42,
    });

    const count = countOccurrences(code, 'async def save_message_to_api(');
    assert.strictEqual(
      count,
      1,
      `"async def save_message_to_api" должна встречаться ровно 1 раз при projectId, найдено: ${count}`
    );
  });

  it('не должно быть других дублированных функций верхнего уровня', () => {
    const botData = makeMinimalBotData();
    const code = generatePythonCode(botData, {
      botName: 'TestBot',
      userDatabaseEnabled: true,
    });

    const topLevelFunctions = [
      'async def init_database(',
      'async def save_user_to_db(',
      'async def get_user_from_db(',
      'async def update_user_data_in_db(',
      'async def init_user_variables(',
      'async def init_all_user_vars(',
      'def replace_variables_in_text(',
      'async def is_admin(',
      'async def is_private_chat(',
    ];

    for (const fn of topLevelFunctions) {
      const count = countOccurrences(code, fn);
      assert.strictEqual(
        count,
        1,
        `"${fn}" должна встречаться ровно 1 раз, найдено: ${count}`
      );
    }
  });
});
